import {COUNTRIES,CONTINENTS,emptyRegion,type User,type RegionData} from '../business';
import {validDesign,DEFAULT_DESIGN} from '../site-context';
import {assert,body,cleanString,hashPassword} from './security';
import {admin,all,audit,first,now,regionList,stmt,territoryList,toRecord,type DB,type ProjectRow} from './store';
export async function adminRoute(db:DB,user:User,request:Request,path:string){if(!path.startsWith('admin/'))return null;admin(user);const method=request.method;
 if(path==='admin/overview'&&method==='GET')return Response.json({users:await all(db,'SELECT id,name,email,role,active,created_at AS createdAt FROM users ORDER BY created_at'),territories:await territoryList(db,false),regions:await regionList(db),projects:(await all<ProjectRow>(db,'SELECT * FROM projects ORDER BY updated_at DESC')).map(toRecord),drafts:await all(db,'SELECT d.id,d.user_id AS userId,u.name AS userName,d.data,d.updated_at AS updatedAt FROM setup_drafts d JOIN users u ON u.id=d.user_id'),customers:(await all<{id:string;owner_id:string;project_id:string;data:string;updated_at:string}>(db,'SELECT * FROM customers')).map(c=>({id:c.id,ownerId:c.owner_id,projectId:c.project_id,data:JSON.parse(c.data),updatedAt:c.updated_at})),quotes:(await all<{snapshot:string;[k:string]:unknown}>(db,'SELECT id,number,project_id AS projectId,owner_id AS ownerId,currency,status,snapshot,created_at AS createdAt FROM quotes ORDER BY created_at DESC')).map(q=>({...q,snapshot:JSON.parse(q.snapshot)})),events:await all(db,'SELECT e.id,e.type,e.project_id AS projectId,e.created_at AS createdAt,u.name AS userName FROM events e JOIN users u ON e.user_id=u.id ORDER BY e.created_at DESC LIMIT 100')});
 if(path==='admin/users'&&method==='POST'){const input=await body(request),id=input.id||crypto.randomUUID(),email=cleanString(input.email).toLowerCase(),name=cleanString(input.name);assert(name&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)&&['admin','sales'].includes(input.role));assert(typeof input.active==='boolean');const old=await first<User>(db,'SELECT id,name,email,role,active FROM users WHERE id=?',id);if(old?.id===user.id)assert(input.active&&input.role==='admin','Kendi yönetici erişiminizi kapatamazsınız.');const duplicate=await first(db,'SELECT id FROM users WHERE email=? AND id<>?',email,id);assert(!duplicate,'Bu e-posta zaten kayıtlı.',409);
  const password=input.password?await hashPassword(input.password):null;assert(old||password,'Yeni kullanıcı için şifre gerekli.');const batch=old?[stmt(db,'UPDATE users SET name=?,email=?,role=?,active=? WHERE id=?',name,email,input.role,input.active?1:0,id)]:[stmt(db,'INSERT INTO users(id,name,email,password_hash,role,active,created_at) VALUES(?,?,?,?,?,?,?)',id,name,email,password,input.role,input.active?1:0,now())];if(old&&password)batch.push(stmt(db,'UPDATE users SET password_hash=? WHERE id=?',password,id));if(old&&(password||!input.active||old.role!==input.role))batch.push(stmt(db,'DELETE FROM sessions WHERE user_id=?',id));batch.push(audit(db,user.id,old?'user.updated':'user.created',{id,name,email,role:input.role,active:input.active,passwordChanged:!!password}));await db.batch(batch);return Response.json({id});
 }
 if(path==='admin/territories'&&method==='POST'){const input=await body(request),continent=cleanString(input.continent),country=cleanString(input.country)||null;assert(CONTINENTS.some(c=>c.code===continent));assert(!country||COUNTRIES.some(c=>c.code===country&&c.continent===continent));const rep=await first<User>(db,'SELECT id,name,email,role,active FROM users WHERE id=?',input.userId);assert(rep?.active,'Aktif bir kullanıcı seçin.');const key=country?`country:${country}`:`continent:${continent}`;await db.batch([stmt(db,'INSERT INTO territories(key,continent,country,user_id) VALUES(?,?,?,?) ON CONFLICT(key) DO UPDATE SET user_id=excluded.user_id',key,continent,country,rep.id),audit(db,user.id,'territory.assigned',{key,continent,country,userId:rep.id})]);return Response.json({ok:true})}
 if(path==='admin/territories'&&method==='DELETE'){const input=await body(request);await db.batch([stmt(db,'DELETE FROM territories WHERE key=?',cleanString(input.key)),audit(db,user.id,'territory.removed',{key:input.key})]);return Response.json({ok:true})}
 if(path==='admin/regions'&&method==='POST'){const input=await body(request),id=input.id||crypto.randomUUID(),country=cleanString(input.country),name=cleanString(input.name);assert(COUNTRIES.some(c=>c.code===country)&&name);const supplied=input.data||{},data:RegionData={...emptyRegion};for(const k of ['standard','source','snowZone','seismicZone','notes'] as const)data[k]=cleanString(supplied[k],k==='notes'?1500:500);for(const k of ['snowLoad','seismicPga','windSpeed','soilBearing'] as const)data[k]=supplied[k]??null;data.corrosion=supplied.corrosion;data.approved=supplied.approved===true;assert(validDesign({...DEFAULT_DESIGN,...data}));assert(!data.source||/^https:\/\//.test(data.source),'Kaynak HTTPS bağlantısı olmalı.');assert(!data.approved||(data.source&&data.standard&&data.snowZone&&data.seismicZone&&data.snowLoad!==null&&data.seismicPga!==null),'Onay için kaynak, standart, zonlar, kar yükü ve PGA gerekli.');const old=await first<{country:string;revision:number}>(db,'SELECT country,revision FROM regions WHERE id=?',id);if(old){assert(old.country===country,'Mevcut bölgenin ülkesi değiştirilemez.');assert(input.revision===old.revision,'Bölge başka bir oturumda değişti.',409)}const revision=(old?.revision||0)+1;const time=now(),write=old?stmt(db,'UPDATE regions SET name=?,data=?,revision=?,updated_at=?,updated_by=? WHERE id=? AND revision=?',name,JSON.stringify(data),revision,time,user.id,id,old.revision):stmt(db,'INSERT INTO regions(id,country,name,data,revision,updated_at,updated_by) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING',id,country,name,JSON.stringify(data),revision,time,user.id);const result=await db.batch([write,stmt(db,'INSERT INTO events(id,user_id,type,data,created_at) SELECT ?,?,?,?,? WHERE changes()=1',crypto.randomUUID(),user.id,'region.updated',JSON.stringify({id,country,name,data,revision}),time)]);assert(result[0].meta.changes===1,'Bölge başka bir oturumda değişti.',409);return Response.json({id,revision})}
 if(path==='admin/assign-project'&&method==='POST'){const input=await body(request),rep=await first<User>(db,'SELECT id,name,email,role,active FROM users WHERE id=?',input.userId);assert(rep?.active,'Aktif bir kullanıcı seçin.');assert(await first(db,'SELECT id FROM projects WHERE id=?',input.projectId),'Proje bulunamadı.',404);await db.batch([stmt(db,'UPDATE projects SET owner_id=?,sales_rep_id=?,revision=revision+1,updated_at=? WHERE id=?',rep.id,rep.id,now(),input.projectId),stmt(db,'UPDATE customers SET owner_id=? WHERE project_id=?',rep.id,input.projectId),audit(db,user.id,'project.assigned',{userId:rep.id},input.projectId)]);return Response.json({ok:true})}
 return null;
}
