import {COUNTRIES,emptyLocation,representativeFor,type Location,type User} from '../business';
import {parseProject,validCustomer,grainIds,SILO_KINDS,type Project} from '../editor';
import {DEFAULT_DESIGN} from '../site-context';
import {buildBusy} from '../installation';
import {ApiError,assert,body,cleanString} from './security';
import {all,audit,first,now,regionList,run,stmt,territoryList,toRecord,visibleProject,type DB,type ProjectRow} from './store';
export function validateLocation(value:unknown):Location{const v=(value||emptyLocation) as Location;assert(['countryCode','regionId','city','address'].every(k=>typeof v[k as keyof Location]==='string'&&v[k as keyof Location].length<=300));assert(!v.countryCode||COUNTRIES.some(c=>c.code===v.countryCode));return{countryCode:v.countryCode,regionId:v.regionId,city:v.city,address:v.address}}
export async function enforceLocation(db:DB,user:User,p:Project,old?:ProjectRow|null){
 const location=validateLocation(p.location),territories=await territoryList(db),sameCountry=old?.country===location.countryCode;
 const rep=representativeFor(location.countryCode,territories);
 if(location.countryCode&&user.role!=='admin'&&!sameCountry)assert(rep===user.id,'Bu ülke satış bölgenize atanmamış.',403);
 const previous=old?JSON.parse(old.data) as Project:null,selectedRegion=(await regionList(db)).find(r=>r.id===location.regionId);assert(!location.regionId||selectedRegion?.country===location.countryCode,'Bölge ülkeyle eşleşmiyor.');
 // Refresh the editable project from the current approved profile. Issued quotes remain immutable snapshots.
 const region=selectedRegion;p.design={...DEFAULT_DESIGN,location:[location.city,region?.name,location.countryCode].filter(Boolean).join(' · '),throughput:p.design?.throughput??null};delete p.loadProfile;
 if(region){const d=region.data;p.loadProfile={regionId:region.id,revision:region.revision,name:region.name,source:d.source,snowZone:d.snowZone,seismicZone:d.seismicZone,approved:d.approved,capturedAt:previous?.loadProfile?.regionId===region.id&&previous.loadProfile.revision===region.revision?previous.loadProfile.capturedAt:now()};if(d.approved)p.design={...p.design,standard:d.standard,snowLoad:d.snowLoad,seismicPga:d.seismicPga,windSpeed:d.windSpeed,soilBearing:d.soilBearing,corrosion:d.corrosion}}
 p.location=location;return sameCountry?old?.sales_rep_id||rep:rep;
}
function eventType(old:Project|null,p:Project){if(!old)return'project.created';if(old.items.length!==p.items.length)return p.items.length>old.items.length?'equipment.added':'equipment.removed';if(JSON.stringify(old.items)!==JSON.stringify(p.items))return'equipment.changed';if(JSON.stringify(old.customer)!==JSON.stringify(p.customer))return'customer.updated';if(JSON.stringify(old.construction)!==JSON.stringify(p.construction))return'construction.checkpoint';return'project.updated'}
export async function projectRoute(db:DB,user:User,request:Request,path:string){const method=request.method;
 if(path==='workspace'&&method==='GET')return Response.json({user,projects:(await all<ProjectRow>(db,user.role==='admin'?'SELECT * FROM projects WHERE archived=0 ORDER BY updated_at DESC':'SELECT * FROM projects WHERE archived=0 AND (owner_id=? OR sales_rep_id=?) ORDER BY updated_at DESC',...(user.role==='admin'?[]:[user.id,user.id]))).map(toRecord),draft:JSON.parse((await first<{data:string}>(db,'SELECT data FROM setup_drafts WHERE user_id=? ORDER BY updated_at DESC LIMIT 1',user.id))?.data||'null'),knownProjectIds:user.role==='admin'?(await all<{id:string}>(db,'SELECT id FROM projects')).map(p=>p.id):[],drafts:(await all<{data:string}>(db,'SELECT data FROM setup_drafts WHERE user_id=? ORDER BY updated_at DESC',user.id)).map(d=>JSON.parse(d.data)),territories:await territoryList(db),regions:await regionList(db),representatives:await all(db,'SELECT id,name FROM users WHERE active=1')});
 if(path==='draft'&&method==='PUT'){const input=await body(request);assert(typeof input.id==='string'&&input.id.length<=100&&Number.isInteger(input.step)&&input.step>=0&&input.step<=2);const s=input.setup;assert(s&&typeof s.name==='string'&&s.name.length<=100&&(s.grain===''||grainIds.includes(s.grain))&&['inland','port'].includes(s.facility)&&SILO_KINDS.includes(s.preferredSilo));assert(['width','depth','density','target'].every(k=>typeof s[k]==='number'&&Number.isFinite(s[k])&&s[k]>=0&&s[k]<=100000));const location=validateLocation(input.location);const data={id:input.id,step:input.step,setup:s,location};const existing=await first<{user_id:string}>(db,'SELECT user_id FROM setup_drafts WHERE id=?',input.id);assert(!existing||existing.user_id===user.id,'Taslak bulunamadı.',404);await db.batch([stmt(db,'INSERT INTO setup_drafts(id,user_id,data,updated_at) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at WHERE setup_drafts.user_id=excluded.user_id',input.id,user.id,JSON.stringify(data),now()),audit(db,user.id,'setup.saved',data)]);return Response.json({ok:true})}
 if(path==='draft'&&method==='DELETE'){const input=await body(request);await run(db,'DELETE FROM setup_drafts WHERE user_id=? AND id=?',user.id,cleanString(input.id));return Response.json({ok:true})}
 const match=path.match(/^projects\/([^/]+)(?:\/(archive|customer|quotes|history|restore))?$/);if(!match)return null;const [,id,action]=match;
 if(method==='PUT'&&!action){const input=await body(request);assert(typeof input.requestId==='string'&&input.requestId.length<=100&&Number.isInteger(input.revision)&&input.revision>=0);const receipt=await first<{user_id:string;data:string}>(db,'SELECT user_id,data FROM events WHERE id=?',input.requestId);if(receipt){assert(receipt.user_id===user.id,'İstek erişimi reddedildi.',403);const row=await visibleProject(db,user,id),ack=JSON.parse(receipt.data);assert(ack.project?.id===id&&Number.isInteger(ack.revision),'İstek kimliği başka bir işlemde kullanılmış.',409);return Response.json({...toRecord(row),project:ack.project,revision:ack.revision})}
  let p:Project;try{p=parseProject(input.project)}catch{throw new ApiError(400,'Proje verileri geçersiz.')};assert(p.id===id);const old=await first<ProjectRow>(db,'SELECT * FROM projects WHERE id=?',id);if(old){await visibleProject(db,user,id);assert(!old.archived,'Proje arşivlenmiş.',409);assert(old.revision===input.revision,'Proje başka bir oturumda değişti. Yerel değişiklikler korundu; yeniden yükleyip kontrol edin.',409)}else assert(input.revision===0,'Proje sürümü bulunamadı.',409);
  const rep=await enforceLocation(db,user,p,old),time=now(),revision=(old?.revision||0)+1;p.createdAt=old?JSON.parse(old.data).createdAt:time;p.updatedAt=time;
  const json=JSON.stringify(p),owner=old?.owner_id||user.id,event=eventType(old?JSON.parse(old.data):null,p);
  const write=old?stmt(db,'UPDATE projects SET data=?,name=?,country=?,region_id=?,sales_rep_id=?,revision=?,updated_at=? WHERE id=? AND revision=?',json,p.name,p.location?.countryCode||null,p.location?.regionId||null,rep,revision,time,id,old.revision):stmt(db,'INSERT INTO projects(id,owner_id,sales_rep_id,name,country,region_id,data,revision,created_at,updated_at,archived) VALUES(?,?,?,?,?,?,?,?,?,?,0) ON CONFLICT(id) DO NOTHING',id,owner,rep,p.name,p.location?.countryCode||null,p.location?.regionId||null,json,revision,time,time);
  const batch=[write,stmt(db,'INSERT INTO events(id,user_id,project_id,type,data,created_at) SELECT ?,?,?,?,?,? WHERE changes()=1',input.requestId,user.id,id,event,JSON.stringify({revision,project:p,...(input.legacy?{legacyOriginal:input.project}:{})}),time)];
  if(p.customer)batch.push(stmt(db,'INSERT INTO customers(id,owner_id,project_id,data,updated_at) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM events WHERE id=?) ON CONFLICT(project_id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at',id,rep||owner,id,JSON.stringify(p.customer),time,input.requestId));
  const result=await db.batch(batch);assert(result[0].meta.changes===1,'Eşzamanlı düzenleme algılandı. Yerel değişiklikler korundu.',409);return Response.json({project:p,revision,ownerId:owner,salesRepId:rep,archived:0});
 }
 const row=await visibleProject(db,user,id);
 if(!action&&method==='GET')return Response.json(toRecord(row));
 if(action==='archive'&&method==='POST'){await db.batch([stmt(db,'UPDATE projects SET archived=1,revision=revision+1,updated_at=? WHERE id=?',now(),id),audit(db,user.id,'project.archived',{},id)]);return Response.json({ok:true})}
 if(action==='restore'&&method==='POST'){await db.batch([stmt(db,'UPDATE projects SET archived=0,revision=revision+1,updated_at=? WHERE id=?',now(),id),audit(db,user.id,'project.restored',{},id)]);return Response.json({ok:true})}
 if(action==='history'&&method==='GET')return Response.json(await all(db,'SELECT e.id,e.type,e.data,e.created_at AS createdAt,u.name AS userName FROM events e JOIN users u ON u.id=e.user_id WHERE project_id=? ORDER BY e.created_at DESC LIMIT 300',id));
 if(action==='customer'&&method==='PUT'){const data=await body(request);assert(['firstName','lastName','company','email','phone','country','address'].every(k=>typeof data[k]==='string'&&data[k].length<=300));await db.batch([stmt(db,'INSERT INTO customers(id,owner_id,project_id,data,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(project_id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at',id,row.sales_rep_id||row.owner_id,id,JSON.stringify(data),now()),audit(db,user.id,'customer.draft',data,id)]);return Response.json({ok:true})}
 if(action==='customer'&&method==='GET')return Response.json(JSON.parse((await first<{data:string}>(db,'SELECT data FROM customers WHERE project_id=?',id))?.data||'null'));
 if(action==='quotes'&&method==='POST'){
  const input=await body(request);assert(typeof input.requestId==='string'&&input.requestId.length<=100);const exists=await first(db,'SELECT id,number FROM quotes WHERE request_id=? AND project_id=?',input.requestId,id);if(exists)return Response.json(exists);
  const p=JSON.parse(row.data) as Project;assert(!row.archived&&p.items.length>0&&validCustomer(p.customer!)&&!buildBusy(p),'Teklif için kurulum ve müşteri bilgilerini tamamlayın.');assert(input.revision===row.revision,'Teklif öncesi proje değişti. Tekrar deneyin.',409);
  const quoteId=crypto.randomUUID(),number=`MY-${new Date().getUTCFullYear()}-${quoteId.slice(0,8).toUpperCase()}`,snapshot={project:p,customer:p.customer,pricingStatus:'not_configured',total:null,projectRevision:row.revision},time=now();
  const result=await db.batch([stmt(db,'INSERT INTO quotes(id,number,request_id,project_id,owner_id,customer_id,currency,status,snapshot,created_at) SELECT ?,?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM projects WHERE id=? AND revision=? AND archived=0)',quoteId,number,input.requestId,id,row.sales_rep_id||row.owner_id,id,p.currency,'pricing_pending',JSON.stringify(snapshot),time,id,row.revision),stmt(db,'INSERT INTO events(id,user_id,project_id,type,data,created_at) SELECT ?,?,?,?,?,? WHERE changes()=1',crypto.randomUUID(),user.id,id,'quote.created',JSON.stringify({quoteId,number,revision:row.revision}),time)]);assert(result[0].meta.changes===1,'Teklif öncesi proje değişti.',409);return Response.json({id:quoteId,number,snapshot});
 }
 return null;
}
