import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import {createItem,createProject,parseProject,type Setup} from '../lib/editor';
import {instantiateBatch,instantiateWalkways,advanceConstruction,alignSiloChange} from '../lib/installation';
import {connectElevator,elevatorAccessDecks,accessIssue,pruneAccess} from '../lib/access-network';
import {walkwayBarriers} from '../lib/walkway-barriers';
import {manualItem,manualFacility} from '../lib/manual-models';
import {roofPanelCount} from '../lib/roof-details';
import {disposeModel} from '../lib/models';
const setup:Setup={name:'Access test',grain:'wheat',density:769,target:0,width:100,depth:100,preferredSilo:'flat',facility:'inland',language:'tr',currency:'USD'};
function facility(){let p=instantiateBatch(createProject(setup),createItem('flat'),{count:9,columns:3});p={...p,construction:advanceConstruction(p.construction!,100000)};p=instantiateWalkways(p);return{...p,construction:undefined,items:[...p.items,createItem('elevator',23,7)]}}
test('unconnected catwalks close both ends and keep toe boards',()=>{const i=createItem('walkway'),barriers=walkwayBarriers(i,[i]);assert.equal(barriers.length,4);for(const side of ['left','right'])assert.ok(barriers.some(b=>b.side===side&&b.start===-i.depth/2&&b.end===i.depth/2));const model=manualItem(i);let ends=0;model.traverse(o=>{if(o.name==='Catwalk end closure')ends++});assert.equal(ends,2);disposeModel(model)});
test('a T junction opens only its connected side and preserves the opposite barrier',()=>{const a={...createItem('walkway'),width:12,y:16},b={...createItem('walkway',0,3),width:6,rotation:90,y:16};const rails=walkwayBarriers(a,[a,b]);assert.equal(rails.filter(r=>r.side==='front').length,2);assert.deepEqual(rails.filter(r=>r.side==='back'),[{side:'back',start:-6,end:6}]);assert.ok(!walkwayBarriers(b,[a,b]).some(r=>r.side==='right'));assert.ok(walkwayBarriers(b,[a,b]).some(r=>r.side==='left'));assert.equal(walkwayBarriers(a,[a,{...b,y:19}]).length,4)});
test('collinear touching paths open their shared ends without opening exposed sides',()=>{const a={...createItem('walkway'),width:10},b={...createItem('walkway',10,0),width:10};const rails=walkwayBarriers(a,[a,b]);assert.equal(rails.some(r=>r.side==='right'),false);assert.equal(rails.some(r=>r.side==='left'),true);assert.ok(rails.some(r=>r.side==='front'&&r.end-r.start===10))});
test('roof seams reach the eave and align with wall stiffeners',()=>{const item=createItem('flat'),model=manualItem(item);model.updateMatrixWorld(true);const seams=model.getObjectByName('Roof sheet seams')!,stiffeners:T.Object3D[]=[];model.traverse(o=>{if(o.name==='Wall stiffener')stiffeners.push(o)});assert.equal(seams.children.length,roofPanelCount(item.width/2));assert.equal(stiffeners.length,seams.children.length);seams.children.forEach((obj,n)=>{const mesh=obj as T.Mesh<T.CylinderGeometry>,p=new T.Vector3(0,-mesh.geometry.parameters.height/2,0).applyMatrix4(mesh.matrixWorld);assert.ok(Math.abs(p.y-(item.height+.4+.055))<1e-6);assert.ok(Math.abs(Math.hypot(p.x,p.z)-(item.width/2+.12))<1e-6);assert.equal(obj.userData.angle,stiffeners[n].userData.angle)});for(const name of ['Roof ladder','Eave guardrail','Eave flashing','Eave air vent','Roof exhaust fan'])assert.ok(model.getObjectByName(name),name);disposeModel(model)});
test('the user layout connects the elevator to both adjacent rows without moving it',()=>{const p=facility(),e=p.items.at(-1)!,items=connectElevator(p,e.id),next={...p,items},linked=items.at(-1)!;assert.deepEqual([linked.x,linked.z,linked.height],[23,7,24]);assert.equal(linked.access!.walkwayIds.length,2);const targets=linked.access!.walkwayIds.map(id=>items.find(w=>w.id===id)!);assert.deepEqual(targets.map(w=>w.z).sort((a,b)=>a-b),[0,15.2]);const decks=elevatorAccessDecks(items);assert.ok(decks.length>=10);assert.ok(decks.every(i=>i.rotation===0||i.rotation===90));assert.equal(accessIssue(next),null);assert.deepEqual(parseProject(JSON.parse(JSON.stringify(next))),JSON.parse(JSON.stringify(next)));const scene=manualFacility(next);assert.ok(scene.getObjectByName('Elevator catwalk connections'));assert.ok(scene.getObjectByName('Elevator caged access ladder'));scene.updateMatrixWorld(true);scene.traverse(o=>assert.ok(o.matrixWorld.elements.every(Number.isFinite)));disposeModel(scene)});
test('connection validation rejects absent routes, large gaps, inadequate height and obstructions',()=>{const p=facility(),e=p.items.at(-1)!;assert.throws(()=>connectElevator({...p,items:[e]},e.id),/connectionMissing/);assert.throws(()=>connectElevator({...p,items:p.items.map(i=>i.id===e.id?{...i,x:43}:i)},e.id),/connectionDistance/);assert.throws(()=>connectElevator({...p,items:p.items.map(i=>i.id===e.id?{...i,height:8}:i)},e.id),/connectionHeight/);const obstacle={...createItem('tower',25,7),width:2,depth:2,height:28};assert.throws(()=>connectElevator({...p,items:[...p.items,obstacle]},e.id),/overlap/)});
test('silo edits preserve route identities and access links; deleting paths removes stale links',()=>{const p=facility(),linked={...p,items:connectElevator(p,p.items.at(-1)!.id)},silo=linked.items[0],oldIds=linked.items.at(-1)!.access!.walkwayIds;const moved=alignSiloChange(linked,{...silo,height:silo.height+1});assert.deepEqual(moved.find(i=>i.kind==='elevator')!.access!.walkwayIds,oldIds);assert.equal(accessIssue({...linked,items:moved}),null);const noPaths=pruneAccess(moved.filter(i=>i.kind!=='walkway'));assert.equal(noPaths.find(i=>i.kind==='elevator')!.access,undefined);assert.throws(()=>parseProject({...linked,items:linked.items.map(i=>i.kind==='elevator'?{...i,access:{walkwayIds:['missing']}}:i)}));});
