import {test} from 'node:test';
import {sqliteDatabase} from '../lib/server/sqlite';
import assert from 'node:assert/strict';
import {DatabaseSync,backup} from 'node:sqlite';
import {readFileSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {handleApi} from '../lib/server/handler';
import {digest,hashPassword,verifyPassword} from '../lib/server/security';
import {createProject,createItem,emptyCustomer,type Project} from '../lib/editor';
import {emptyRegion,emptyLocation,representativeFor,type ProjectRecord,type Workspace} from '../lib/business';
import {DEFAULT_DESIGN} from '../lib/site-context';
import {ProjectSync,RequestError} from '../lib/api-client';
import {instantiateBatch,advanceConstruction} from '../lib/installation';
const origin='http://127.0.0.1:5188',password='Local-test-only-19426!';
const hash=await hashPassword(password);
const migrations=['0000_neat_marten_broadcloak.sql','0001_slippery_famine.sql'].map(file=>readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8')).join('\n');
function fixture(path=':memory:'){
 const sql=new DatabaseSync(path);sql.exec('PRAGMA foreign_keys=ON;'+migrations);
 for(const [id,role] of [['admin','admin'],['sales-a','sales'],['sales-b','sales']]){sql.prepare('INSERT INTO users(id,email,name,password_hash,role,active,created_at) VALUES(?,?,?,?,?,1,?)').run(id,id+'@test.local',id,hash,role,new Date().toISOString());sql.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').run(digest(id+'-session'),id,Date.now()+3600000)}
 const d1=sqliteDatabase(sql);
 const call=async(user:string|null,path:string,method='GET',data?:unknown,csrf=true)=>{const headers:Record<string,string>={};if(user)headers.cookie='mysilo_session='+user+'-session';if(data!==undefined)headers['content-type']='application/json';if(csrf)headers.origin=origin;const response=await handleApi(d1,new Request(origin+'/api/'+path,{method,headers,body:data===undefined?undefined:JSON.stringify(data)}));return {status:response.status,data:await response.json() as any,headers:response.headers}};
 return {sql,d1,call};
}
function project(){return createProject({name:'Isolated test facility',grain:'wheat',density:769,target:1000,facility:'inland',width:100,depth:100,preferredSilo:'flat',language:'tr',currency:'TRY',location:{...emptyLocation,countryCode:'TR',city:'Test city'}})}
async function territory(f:ReturnType<typeof fixture>,userId='sales-a'){assert.equal((await f.call('admin','admin/territories','POST',{continent:'AS',country:'TR',userId})).status,200)}
async function save(f:ReturnType<typeof fixture>,p:Project,revision=0,user='sales-a',requestId=crypto.randomUUID()){return f.call(user,'projects/'+p.id,'PUT',{project:p,revision,requestId})}
test('password hashes use random salt, verify correctly, and reject weak or oversized input',async()=>{const second=await hashPassword(password);assert.notEqual(hash,second);assert.equal(await verifyPassword(password,hash),true);assert.equal(await verifyPassword('wrong',hash),false);await assert.rejects(hashPassword('short'));await assert.rejects(hashPassword('x'.repeat(129)))});
test('authentication uses HttpOnly sessions, rejects cross-origin writes and protects admin endpoints',async()=>{const f=fixture();try{assert.equal((await f.call(null,'workspace')).status,401);assert.equal((await f.call('sales-a','admin/overview')).status,403);assert.equal((await f.call(null,'auth/login','POST',{email:'admin@test.local',password},false)).status,403);const login=await f.call(null,'auth/login','POST',{email:'admin@test.local',password});assert.equal(login.status,200);assert.match(login.headers.get('set-cookie')!,/HttpOnly; SameSite=Strict/);assert.equal(login.data.user.password_hash,undefined);f.sql.prepare('UPDATE users SET active=0 WHERE id=?').run('sales-a');assert.equal((await f.call('sales-a','workspace')).status,401);assert.equal((await f.call('admin','auth/logout','POST',{})).status,200);assert.equal((await f.call('admin','workspace')).status,401)}finally{f.sql.close()}});
test('login attempts are rate limited and a disabled account cannot authenticate',async()=>{const f=fixture();try{f.sql.prepare('UPDATE users SET active=0 WHERE id=?').run('sales-b');assert.equal((await f.call(null,'auth/login','POST',{email:'sales-b@test.local',password})).status,401);f.sql.prepare('INSERT INTO auth_attempts(key,count,reset_at) VALUES(?,8,?)').run(digest('login:admin@test.local'),Date.now()+900000);assert.equal((await f.call(null,'auth/login','POST',{email:'admin@test.local',password})).status,429)}finally{f.sql.close()}});
test('country assignment overrides continent routing and salespeople cannot choose another representative',async()=>{const f=fixture();try{await f.call('admin','admin/territories','POST',{continent:'AS',country:'',userId:'sales-b'});await territory(f);const territories=(await f.call('sales-a','workspace')).data.territories;assert.equal(representativeFor('TR',territories),'sales-a');assert.equal(representativeFor('JP',territories),'sales-b');const p=project(),created=await save(f,p);assert.equal(created.status,200);assert.equal(created.data.salesRepId,'sales-a');assert.equal((await f.call('sales-b','projects/'+p.id)).status,404);assert.equal((await f.call('sales-b','workspace')).data.projects.length,0);assert.equal((await save(f,project(),0,'sales-b')).status,403);assert.equal((await f.call('admin','admin/overview')).data.projects.length,1)}finally{f.sql.close()}});
test('project writes are versioned, idempotent and atomic; stale edits cannot overwrite saved placement',async()=>{const f=fixture();try{await territory(f);const p=project(),requestId=crypto.randomUUID();p.items=[createItem('cleaner',-20,-20)];const initial=await save(f,p,0,'sales-a',requestId);assert.equal(initial.status,200);assert.equal(initial.data.revision,1);const changed={...initial.data.project,items:[{...p.items[0],x:20}]};assert.equal((await save(f,changed,1)).status,200);const retry=await save(f,p,0,'sales-a',requestId);assert.equal(retry.data.revision,1);const conflict=await save(f,{...p,items:[{...p.items[0],x:30}]},1);assert.equal(conflict.status,409);assert.equal((await f.call('sales-a','projects/'+p.id)).data.project.items[0].x,20);assert.equal(f.sql.prepare('SELECT count(*) AS n FROM events WHERE project_id=?').get(p.id)!.n,2);const forged={...p,items:[{...p.items[0],width:NaN}]};assert.equal((await save(f,forged,2)).status,400)}finally{f.sql.close()}});
test('the server derives loads from the approved site profile and records the applied profile revision',async()=>{const f=fixture();try{await territory(f);const profile={country:'TR',name:'Test region — synthetic values, isolated database only',data:{...emptyRegion,approved:true,standard:'TEST-ONLY',source:'https://example.com/engineering-test',snowZone:'test-snow',seismicZone:'test-PGA',snowLoad:1.25,seismicPga:.35}};const region=await f.call('admin','admin/regions','POST',profile);assert.equal(region.status,200);const p=project();p.location!.regionId=region.data.id;p.design={...DEFAULT_DESIGN,snowLoad:0,seismicPga:0};const saved=await save(f,p);assert.equal(saved.status,200);assert.equal(saved.data.project.design.snowLoad,1.25);assert.equal(saved.data.project.design.seismicPga,.35);assert.equal(saved.data.project.loadProfile.revision,1);assert.equal((await f.call('sales-a','admin/regions','POST',profile)).status,403);await f.call('admin','admin/regions','POST',{...profile,id:region.data.id,revision:1,data:{...profile.data,snowLoad:2.5}});const next=await save(f,{...saved.data.project,design:{...saved.data.project.design,snowLoad:0}},1);assert.equal(next.data.project.design.snowLoad,2.5);assert.equal(next.data.project.loadProfile.revision,2);const unknown=await save(f,{...project(),design:{...DEFAULT_DESIGN,snowLoad:4,seismicPga:2}});assert.equal(unknown.data.project.design.snowLoad,null);assert.equal(unknown.data.project.design.seismicPga,null);const invalid={...p,id:crypto.randomUUID(),location:{...p.location!,countryCode:'DE'}};assert.equal((await save(f,invalid,0,'admin')).status,400)}finally{f.sql.close()}});
test('quotes persist customer data and an immutable full snapshot with no fabricated prices',async()=>{const f=fixture();try{await territory(f);const p=project();p.items=[createItem('flat',0,0)];p.customer={...emptyCustomer,firstName:'Test',lastName:'Customer',company:'QA only',email:'customer@example.test',phone:'+90 555 000 0000'};const saved=await save(f,p);assert.equal(saved.status,200);const requestId=crypto.randomUUID(),q=await f.call('sales-a','projects/'+p.id+'/quotes','POST',{requestId,revision:1});assert.equal(q.status,200);assert.match(q.data.number,/^MY-/);const duplicate=await f.call('sales-a','projects/'+p.id+'/quotes','POST',{requestId,revision:1});assert.equal(duplicate.data.id,q.data.id);await save(f,{...saved.data.project,name:'Changed name',customer:{...p.customer,company:'Changed company'}},1);const overview=(await f.call('admin','admin/overview')).data;assert.equal(overview.quotes.length,1);assert.equal(overview.customers[0].data.company,'Changed company');assert.equal(overview.quotes[0].snapshot.project.name,p.name);assert.equal(overview.quotes[0].snapshot.customer.company,'QA only');assert.equal(overview.quotes[0].snapshot.total,null);assert.equal(overview.quotes[0].currency,'TRY');assert.equal((await f.call('sales-b','projects/'+p.id+'/quotes','POST',{requestId:crypto.randomUUID(),revision:2})).status,404)}finally{f.sql.close()}});
test('multiple setup drafts survive independently and user isolation also covers drafts and customer records',async()=>{const f=fixture();try{await territory(f);const p=project();const d={id:'draft-one',setup:p,location:p.location,step:1};assert.equal((await f.call('sales-a','draft','PUT',d)).status,200);assert.equal((await f.call('sales-a','draft','PUT',{...d,id:'draft-two',step:2})).status,200);assert.equal((await f.call('sales-a','workspace')).data.drafts.length,2);assert.equal((await f.call('sales-b','workspace')).data.drafts.length,0);assert.equal((await f.call('sales-b','draft','PUT',d)).status,404);await f.call('sales-a','draft','DELETE',{id:'draft-one'});assert.equal((await f.call('sales-a','workspace')).data.drafts.length,1);await save(f,p);assert.equal((await f.call('sales-a','projects/'+p.id+'/customer','PUT',{...emptyCustomer,firstName:'Partial'})).status,200);assert.equal((await f.call('sales-b','projects/'+p.id+'/customer')).status,404);assert.equal((await f.call('admin','admin/overview')).data.customers[0].data.firstName,'Partial')}finally{f.sql.close()}});
test('archiving is reversible, retains revisions, and restores the saved project',async()=>{const f=fixture();try{await territory(f);const p=project();await save(f,p);assert.equal((await f.call('sales-a','projects/'+p.id+'/archive','POST',{})).status,200);assert.equal((await f.call('sales-a','workspace')).data.projects.length,0);assert.equal((await f.call('admin','admin/overview')).data.projects[0].archived,1);assert.equal((await f.call('sales-a','projects/'+p.id+'/restore','POST',{})).status,200);assert.equal((await f.call('sales-a','workspace')).data.projects[0].project.name,p.name)}finally{f.sql.close()}});
test('database backup reopens with projects, owners, revisions and audit history intact',async()=>{const dir=mkdtempSync(join(tmpdir(),'mysilo-db-')),path=join(dir,'main.sqlite'),f=fixture(path);try{await territory(f);const p=project();await save(f,p);await backup(f.sql,join(dir,'backup.sqlite'));const restored=new DatabaseSync(join(dir,'backup.sqlite'),{readOnly:true});assert.equal(restored.prepare('SELECT owner_id FROM projects WHERE id=?').get(p.id)!.owner_id,'sales-a');assert.equal(restored.prepare('SELECT count(*) AS n FROM events WHERE project_id=?').get(p.id)!.n,1);restored.close()}finally{f.sql.close();rmSync(dir,{recursive:true,force:true})}});
test('a failed project save remains in the per-user outbox and retries with the same idempotency key',async()=>{const p=project(),store=new Map<string,string>(),storage={getItem:(k:string)=>store.get(k)||null,setItem:(k:string,v:string)=>{store.set(k,v)}},original=globalThis.fetch;const requests:any[]=[];let offline=true;globalThis.fetch=async(_url,options)=>{const body=JSON.parse(options!.body as string);requests.push(body);if(offline)throw new Error('offline');return Response.json({project:body.project,revision:1,ownerId:'sales-a',salesRepId:'sales-a',archived:0})};try{const sync=new ProjectSync('sales-a',[],storage);await assert.rejects(sync.save(p));assert.equal(sync.pending().length,1);const restored=new ProjectSync('sales-a',[],storage);offline=false;await restored.flush();assert.equal(restored.pending().length,0);assert.equal(requests[0].requestId,requests[1].requestId);assert.equal(new ProjectSync('sales-b',[],storage).pending().length,0);assert.equal(restored.revision(p.id),1)}finally{globalThis.fetch=original}});
test('only administrators can create users; account deactivation revokes existing sessions',async()=>{const f=fixture();try{const input={name:'New representative',email:'new@example.test',role:'sales',active:true,password};assert.equal((await f.call('sales-a','admin/users','POST',input)).status,403);const created=await f.call('admin','admin/users','POST',input);assert.equal(created.status,200);const row=f.sql.prepare('SELECT password_hash FROM users WHERE id=?').get(created.data.id)!;assert.notEqual(row.password_hash,password);assert.equal((await f.call(null,'auth/login','POST',{email:input.email,password})).status,200);await f.call('admin','admin/users','POST',{...input,id:created.data.id,password:'',active:false});assert.equal(f.sql.prepare('SELECT COUNT(*) AS n FROM sessions WHERE user_id=?').get(created.data.id)!.n,0);assert.equal((await f.call('admin','admin/users','POST',{id:'admin',name:'Admin',email:'admin@test.local',role:'admin',active:false,password:''})).status,400)}finally{f.sql.close()}});
test('construction checkpoints retain phase, speed and pause after a reload; archived legacy IDs are not imported again',async()=>{const f=fixture();try{await territory(f);const p=instantiateBatch(project(),createItem('flat'),{count:2,columns:2});await save(f,p);const next={...p,construction:{...advanceConstruction(p.construction!,12),speed:8 as const,paused:true}};await save(f,next,1);const restored=(await f.call('sales-a','projects/'+p.id)).data.project;assert.deepEqual(restored.items,p.items);assert.equal(restored.construction.paused,true);assert.equal(restored.construction.speed,8);assert.equal(restored.construction.elapsed,next.construction.elapsed);assert.equal((await f.call('sales-a','projects/'+p.id+'/quotes','POST',{requestId:crypto.randomUUID(),revision:2})).status,400);await f.call('admin','projects/'+p.id+'/archive','POST',{});const adminWorkspace=(await f.call('admin','workspace')).data;assert.equal(adminWorkspace.projects.length,0);assert.ok(adminWorkspace.knownProjectIds.includes(p.id))}finally{f.sql.close()}});
