import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {Box3,Vector3} from 'three';
import {createProject,createItem,parseProject,importProject,loadProjects,storeProject,projectExport,itemIssue,itemBottom,itemCapacity,validSetup,validItem,validCustomer,emptyCustomer,PROJECTS_KEY,KINDS,PRODUCTS,SILO_KINDS,type Setup} from '../lib/editor';
import {LANGUAGES,CURRENCIES,words,t,type TextKey} from '../lib/i18n';
import {manualItem,manualFacility} from '../lib/manual-models';
import {disposeModel} from '../lib/models';
import {DEFAULTS} from '../lib/planner';
import {encodeProject} from '../lib/project';
const setup:Setup={name:'Liman projesi',grain:'corn',density:720,target:6000,facility:'port',width:120,depth:85,preferredSilo:'flat',language:'tr',currency:'USD'};
const customer={...emptyCustomer,firstName:'Demo',lastName:'Müşteri',company:'Test firma',email:'demo@example.com',phone:'+90 555 000 00 00'};
const memory=()=>{const data=new Map<string,string>();return {getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v)}}};
test('named projects start empty and are saved independently',()=>{const store=memory(),a=createProject(setup),b=createProject({...setup,name:'Kara tesisi',facility:'inland',currency:'EUR'});assert.equal(a.items.length,0);assert.notEqual(a.id,b.id);storeProject(store,a);storeProject(store,b);a.items.push(createItem('flat',-20,-20));storeProject(store,a);const restored=loadProjects(store);assert.equal(restored.length,2);assert.deepEqual(restored.find(p=>p.id===a.id),a);assert.deepEqual(restored.find(p=>p.id===b.id),b)});
test('placement detects boundaries, rotations and vertical clearance',()=>{const p=createProject(setup),silo=createItem('flat',0,0);p.items.push(silo);assert.equal(itemIssue(p,silo),null);assert.equal(itemIssue(p,createItem('flat',1,1)),'overlap');assert.equal(itemIssue(p,createItem('flat',58,0)),'outside');const bridge={...createItem('walkway'),width:32,y:18};assert.equal(itemIssue(p,bridge),null);assert.equal(itemIssue(p,{...bridge,y:5}),'overlap');const rotated={...createItem('building',48,0),width:8,depth:20};assert.equal(itemIssue(p,rotated),null);assert.equal(itemIssue(p,{...rotated,rotation:90}),'outside')});
test('all supported products have finite capacity, geometry and local imagery',()=>{for(const kind of KINDS){const item=createItem(kind);assert.ok(validItem(item),kind);const capacity=itemCapacity(item,720);assert.ok(Number.isFinite(capacity));assert.equal(capacity>0,SILO_KINDS.includes(kind as typeof SILO_KINDS[number]));assert.ok(existsSync('public/mysilo/'+PRODUCTS[kind].image));const model=manualItem(item);const bounds=new Box3().setFromObject(model);assert.ok(!bounds.isEmpty());assert.ok(bounds.min.toArray().concat(bounds.max.toArray()).every(Number.isFinite));disposeModel(model)}});
test('equipment dimensions apply to the rendered geometry',()=>{for(const kind of ['elevator','intake','dryer','cleaner'] as const){const i={...createItem(kind),width:9,depth:7,height:22};const model=manualItem(i),box=new Box3().setFromObject(model),size=box.getSize(new Vector3());assert.ok(Math.abs(size.x-i.width)<1e-6,kind);assert.ok(Math.abs(size.z-i.depth)<1e-6,kind);assert.ok(Math.abs(size.y-i.height)<1e-6,kind);assert.ok(Math.abs(box.min.y-itemBottom(i))<1e-6);disposeModel(model)}});
test('project export requires valid customer details and roundtrips edited placement',()=>{const p=createProject(setup);p.items=[{...createItem('building',23,-8),rotation:90},createItem('economic',-30,0)];assert.throws(()=>projectExport(p));assert.equal(validCustomer({...customer,email:'invalid'}),false);p.customer=customer;const raw=projectExport(p),data=JSON.parse(raw);assert.deepEqual(importProject(raw),p);assert.equal(data.summary.pricingStatus,'not_configured');assert.equal(data.summary.componentCount,2);assert.equal(data.summary.capacityTonnes,p.items.reduce((s,i)=>s+itemCapacity(i,p.density),0));const scene=manualFacility(p);assert.equal(scene.userData.project.customer.email,customer.email);disposeModel(scene)});
test('malformed project inputs and unknown fields cannot enter saved project records',()=>{const p=createProject(setup);for(const change of [{width:0},{depth:NaN},{density:10},{currency:'BTC'},{language:'zz'},{name:''},{facility:'ocean'}])assert.equal(validSetup({...setup,...change} as Setup),false);for(const change of [{width:0},{depth:Infinity},{kind:'unknown'},{id:''},{rotation:1000}])assert.equal(validItem({...createItem('flat'),...change} as ReturnType<typeof createItem>),false);assert.throws(()=>parseProject({...p,items:[createItem('flat'),{...createItem('square'),id:''}]}));const store=memory();assert.throws(()=>storeProject(store,{...p,width:-1}));assert.equal(store.getItem(PROJECTS_KEY),null);const cleaned=parseProject({...p,untrusted:42,customer:{...customer,untrusted:42}});assert.ok(!('untrusted' in cleaned));assert.ok(!('untrusted' in cleaned.customer!));assert.throws(()=>importProject(' '.repeat(2_000_001)));assert.throws(()=>importProject('null'));assert.throws(()=>importProject('{}'))});
test('legacy project migrates once into the library without losing the source',()=>{const store=memory(),raw=encodeProject(DEFAULTS);store.setItem('silo-studio:project:v1',raw);const [legacy]=loadProjects(store);assert.equal(legacy.id,'legacy-v1');assert.ok(legacy.items.length>0);storeProject(store,legacy);storeProject(store,createProject(setup));assert.equal(loadProjects(store).length,2);assert.equal(store.getItem('silo-studio:project:v1'),raw)});
test('all seven languages cover every interface label and requested currencies exist',()=>{assert.deepEqual(CURRENCIES,['TRY','USD','EUR','GBP']);assert.equal(LANGUAGES.length,7);for(const key of Object.keys(words) as TextKey[])for(const language of LANGUAGES){assert.equal(words[key].length,7,key);assert.ok(t(language.id,key).trim(),`${language.id}:${key}`)}});
test('asset manifest preserves source attribution for all catalog images',()=>{const data=JSON.parse(readFileSync('public/mysilo/sources.json','utf8'));assert.ok(JSON.stringify(data).includes('mysilo.com'));for(const p of Object.values(PRODUCTS))assert.ok(JSON.stringify(data).includes(p.image),p.image)});
test('binary 3D export contains valid geometry plus customer and placement metadata',async()=>{
 const {GLTFExporter}=await import('three/addons/exporters/GLTFExporter.js');
 class NodeFileReader{result:ArrayBuffer|null=null;onloadend:(()=>void)|null=null;onerror:((e:unknown)=>void)|null=null;readAsArrayBuffer(blob:Blob){blob.arrayBuffer().then(result=>{this.result=result;this.onloadend?.()}).catch(e=>this.onerror?.(e))}}
 const previous=Object.getOwnPropertyDescriptor(globalThis,'FileReader');Object.defineProperty(globalThis,'FileReader',{value:NodeFileReader,configurable:true});
 const p=createProject(setup);p.customer=customer;p.items=KINDS.map((k,n)=>({...createItem(k,(n%4)*24-36,Math.floor(n/4)*18-27),rotation:n===4?90:0}));
 const model=manualFacility(p);
 try{const result=await new GLTFExporter().parseAsync(model,{binary:true});assert.ok(result instanceof ArrayBuffer);const bytes=Buffer.from(result);assert.equal(bytes.toString('ascii',0,4),'glTF');assert.equal(bytes.readUInt32LE(4),2);assert.equal(bytes.readUInt32LE(8),bytes.length);const json=JSON.parse(bytes.toString('utf8',20,20+bytes.readUInt32LE(12)));const extras=json.nodes.find((n:{extras?:{project:unknown}})=>n.extras?.project).extras;assert.deepEqual(extras.project,p);assert.ok(json.meshes.length>=KINDS.length);assert.ok(json.accessors.length>0)}finally{disposeModel(model);if(previous)Object.defineProperty(globalThis,'FileReader',previous);else Reflect.deleteProperty(globalThis,'FileReader')}
});
