import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DEFAULTS,DIAMETERS,GRAINS,binVolume,plan,type Inputs} from '../lib/planner';
import {decodeProject,encodeProject} from '../lib/project';
function verify(p:Inputs){const l=plan(p);if(!l.valid)return;assert.ok(l.total>=p.capacity);assert.ok(l.bins.length>=p.lots);assert.ok(l.bins.length<=36);for(const b of l.bins){assert.ok(Math.abs(b.x)+b.diameter/2<=p.width/2-p.margin+1e-8);assert.ok(Math.abs(b.z)+b.diameter/2<=p.depth/2-p.margin+1e-8);for(const c of l.bins){if(c===b)continue;assert.ok(Math.hypot(b.x-c.x,b.z-c.z)>=(b.diameter+c.diameter)/2+p.gap-1e-8)}}for(const e of l.equipment){assert.ok(Math.abs(e.x)+e.width/2<=p.width/2-p.margin+1e-8,`${e.id} x boundary`);assert.ok(Math.abs(e.z)+e.depth/2<=p.depth/2-p.margin+1e-8,`${e.id} z boundary`);for(const b of l.bins){const dx=Math.max(Math.abs(b.x-e.x)-e.width/2,0),dz=Math.max(Math.abs(b.z-e.z)-e.depth/2,0);assert.ok(Math.hypot(dx,dz)>=b.diameter/2,`${e.id} intersects ${b.id}`)}}for(let i=0;i<l.equipment.length;i++)for(let j=i+1;j<l.equipment.length;j++){const a=l.equipment[i],b=l.equipment[j];assert.ok(Math.abs(a.x-b.x)>=(a.width+b.width)/2||Math.abs(a.z-b.z)>=(a.depth+b.depth)/2,`${a.id} vs ${b.id}`)}}
test('default facility meets storage demand and parcel constraints',()=>{const l=plan(DEFAULTS);assert.ok(l.valid);verify(DEFAULTS);assert.equal(l.bins.length,6);assert.ok(l.equipment.some(e=>e.type==='dryer'));assert.equal(l.total,l.bins.reduce((s,b)=>s+b.capacity,0))});
test('infeasible land yields explicit empty layout, never partial success',()=>{const l=plan({...DEFAULTS,width:25,depth:25,capacity:20000});assert.equal(l.valid,false);assert.equal(l.bins.length,0);assert.ok(l.errors.length>0)});
test('reject invalid numbers and enumerations without entering search',()=>{for(const bad of [{density:NaN},{width:Infinity},{capacity:-1},{lots:2.5},{hours:0},{grain:'sand'},{dryer:'yes'},{diameter:1},{siloType:'water'}]){const l=plan({...DEFAULTS,...bad} as Inputs);assert.equal(l.valid,false);assert.ok(l.errors.length)}});
test('drying balance conserves dry matter on a wet basis',()=>{const p={...DEFAULTS,intake:800,hours:10,moistureIn:25,moistureOut:15},l=plan(p);assert.ok(Math.abs(l.dryOutput*(1-p.moistureOut/100)-l.flow*(1-p.moistureIn/100))<1e-10);assert.ok(Math.abs(l.water-9.411764705882353)<1e-10);assert.equal(plan({...p,moistureIn:15}).water,0)});
test('equipment choices and wet grain warnings follow inputs',()=>{const l=plan({...DEFAULTS,dryer:false,cleaner:false,aeration:false});assert.ok(l.valid);assert.ok(!l.equipment.some(e=>e.type==='dryer'||e.type==='cleaner'||e.type==='wetbin'));assert.ok(l.warnings.some(w=>w.includes('Giriş nemi')));assert.ok(l.warnings.some(w=>w.includes('Havalandırma')))});
test('rotates facility to fit a narrow but long parcel',()=>{const p={...DEFAULTS,width:52,depth:140,capacity:1500,lots:3,dryer:false},l=plan(p);assert.ok(l.valid);assert.equal(l.rotated,true);verify(p)});
test('fixed diameter and hopper catalog limit are honored',()=>{const l=plan({...DEFAULTS,diameter:14.66});assert.ok(l.valid);assert.ok(l.bins.every(b=>b.diameter===14.66));assert.equal(plan({...DEFAULTS,siloType:'hopper',diameter:14.66}).valid,false);const h=plan({...DEFAULTS,siloType:'hopper',capacity:2000,lots:4});assert.ok(h.valid);assert.ok(h.bins.every(b=>b.type==='hopper'&&b.diameter<=11))});
test('capacity scales with density and hopper volume includes lower cone',()=>{const v=binVolume(10,10,'flat');assert.ok(binVolume(10,10,'hopper')>v);const a=plan({...DEFAULTS,diameter:12.83,lots:6,capacity:50,density:400}),b=plan({...DEFAULTS,diameter:12.83,lots:6,capacity:50,density:800});assert.ok(a.valid&&b.valid);assert.equal(b.total,a.total*2)});
test('property sweep validates parcel and collision invariants over 576 scenarios',()=>{let feasible=0;for(const grain of GRAINS)for(const width of [65,90,120,200])for(const depth of [55,85,130])for(const capacity of [1000,6000])for(const siloType of ['flat','hopper'] as const)for(const dryer of [false,true]){const p={...DEFAULTS,grain:grain.id,density:grain.density,width,depth,capacity,siloType,dryer};verify(p);if(plan(p).valid)feasible++}assert.ok(feasible>100)});
test('project roundtrip rejects unsafe or incompatible imports',()=>{assert.deepEqual(decodeProject(encodeProject(DEFAULTS)),DEFAULTS);for(const data of ['{}','null','not json',JSON.stringify({version:2,inputs:DEFAULTS}),JSON.stringify({version:1,inputs:{...DEFAULTS,width:-1}})])assert.throws(()=>decodeProject(data));assert.throws(()=>decodeProject(' '.repeat(1_000_001)));const raw=JSON.stringify({version:1,inputs:{...DEFAULTS,untrusted:'ignore'},layout:{total:999999}});assert.deepEqual(decodeProject(raw),DEFAULTS)});
test('search is deterministic and catalog diameter values are unique',()=>{assert.deepEqual(plan(DEFAULTS),plan(DEFAULTS));assert.equal(new Set(DIAMETERS).size,DIAMETERS.length)});
