'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {Boxes,Settings2,ListChecks,CheckCircle2,Clock3} from 'lucide-react';
import {buildBusy} from '@/lib/installation';
import {BuildStatus} from '@/components/installation-controls';
import {handlingName} from '@/lib/handling-catalog';
import {t} from '@/lib/i18n';
import type {Project} from '@/lib/editor';
export default function EditorDrawer({project,selected,placing,palette,properties,onSelect}:{project:Project;selected:string;placing:boolean;palette:ReactNode;properties:ReactNode;onSelect:(id:string)=>void}){const [tab,setTab]=useState('properties'),busy=buildBusy(project);useEffect(()=>{if(selected||placing)setTab('properties');else if(busy)setTab('installation')},[selected,placing,busy]);return <aside className="editor-drawer"><nav aria-label="Proje araçları" className="drawer-nav">{[{id:'products',name:t(project.language,'equipment'),icon:Boxes},{id:'properties',name:t(project.language,'properties'),icon:Settings2},{id:'installation',name:t(project.language,'installationTab'),icon:ListChecks}].map(({id,name,icon:Icon})=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)} className={tab===id?'active':''}><Icon size={18}/><span>{name}</span></button>)}</nav><div className="drawer-body">{tab==='products'?palette:tab==='properties'?properties:<section className="installation-drawer"><span className="eyebrow">{t(project.language,'installationTracking')}</span><h2>{project.name}</h2><div className={`installation-state ${busy?'working':''}`}>{busy?<Clock3 size={20}/>:<CheckCircle2 size={20}/>}<span>{busy?(t(project.language,'installationOngoing')):(project.items.length?t(project.language,'complete'):t(project.language,'chooseEquipment'))}</span></div><div className="component-list">{project.items.map((i,n)=><button key={i.id} onClick={()=>{onSelect(i.id);setTab('properties')}}><span>{String(n+1).padStart(2,'0')}</span>{handlingName(i,project.language)}<BuildStatus project={project} id={i.id}/></button>)}</div></section>}</div></aside>}
