'use client';
import {handlingName} from '@/lib/handling-catalog';
import {CheckCircle2,Clock3,LoaderCircle,Pause,Play,HardHat} from 'lucide-react';
import {t,nf,type Lang} from '@/lib/i18n';
import {activeStage,constructionStage,totalBuildSeconds,type BatchOptions} from '@/lib/installation';
import type {Project,SiteSettings} from '@/lib/editor';
export function BatchControls({options,onChange,lang,site,onSiteChange}:{site:SiteSettings;onSiteChange:(v:SiteSettings)=>void;options:BatchOptions;onChange:(v:BatchOptions)=>void;lang:Lang}){return <div className="batch-controls"><div className="property-fields"><label className="m-field"><span>{t(lang,'siloCount')}</span><input className="m-input" type="number" min={1} max={60} value={options.count} onChange={e=>{const count=Number(e.target.value);onChange({...options,count,columns:Math.min(options.columns,Math.max(1,count))})}}/></label><label className="m-field"><span>{t(lang,'columns')}</span><input className="m-input" type="number" min={1} max={Math.max(1,options.count)} value={options.columns} onChange={e=>onChange({...options,columns:Number(e.target.value)})}/></label></div><div className="property-fields">{(['setback','siloGap'] as const).map(k=><label className="m-field" key={k}><span>{t(lang,k)} (m)</span><input className="m-input" type="number" min="1" max="30" step=".5" value={site[k]} onChange={e=>onSiteChange({...site,[k]:Number(e.target.value)})}/></label>)}</div></div>}
export function BuildProgress({project,onPause}:{project:Project;onPause:()=>void}){const c=project.construction!;const percent=Math.min(100,Math.floor(c.elapsed/totalBuildSeconds(c)*100)),stage=activeStage(project),activeItem=project.items.find(i=>{const s=constructionStage(c,i.id);return s.stage===stage&&s.progress<1});return <div className="build-progress"><div className="build-progress-top"><HardHat size={19}/><div><strong>{t(project.language,stage)}</strong><small>{activeItem?handlingName(activeItem,project.language):t(project.language,'simulation')}</small></div><span>{nf(project.language,percent,0)}%</span><button className="m-tool" onClick={onPause} aria-label={t(project.language,c.paused?'resume':'pause')}>{c.paused?<Play size={17}/>:<Pause size={17}/>}</button></div><div className="build-progress-track" role="progressbar" aria-label={t(project.language,'simulation')} aria-valuenow={percent} aria-valuemin={0} aria-valuemax={100}><i style={{width:percent+'%'}}/></div></div>}
export function BuildStatus({project,id}:{project:Project;id:string}){const {stage}=constructionStage(project.construction,id);const state=stage==='complete'?'done':stage==='queued'||project.construction?.paused?'queued':'working',label=t(project.language,stage);return <span className={`build-status ${state}`} data-state={state} title={label} aria-label={label}>{state==='done'?<CheckCircle2 size={16}/>:state==='queued'?<Clock3 size={16}/>:<LoaderCircle size={16}/>}</span>}

export function SiloCountControl({options,onChange,lang}:{options:BatchOptions;onChange:(v:BatchOptions)=>void;lang:Lang}){const update=(count:number)=>onChange({...options,count,columns:Math.min(options.columns,Math.max(1,count))});return <label className="build-count"><span>{t(lang,'siloCount')}</span><div><button type="button" aria-label={t(lang,'decreaseCount')} disabled={options.count<=1} onClick={()=>update(Math.max(1,options.count-1))}>−</button><input aria-label={t(lang,'siloCount')} type="number" min={1} max={60} step={1} value={options.count||''} onChange={e=>update(Number(e.target.value))}/><button type="button" aria-label={t(lang,'increaseCount')} disabled={options.count>=60} onClick={()=>update(Math.min(60,options.count+1))}>+</button></div></label>}
