'use client';
import {movementPreview,type MoveScope} from '@/lib/movement';
import {useRef,useState} from 'react';
import {portFrame,shoreBounds} from '@/lib/site-context';
import {loaderTip,reachesVessel} from '@/lib/design-review';
import {handlingName} from '@/lib/handling-catalog';
import {itemFootprint,corners,itemIssue,roundKinds,isSilo,siteSettings,type Item,type Project} from '@/lib/editor';
import {elevatorAccessDecks} from '@/lib/access-network';
import {walkwayPose} from '@/lib/walkway-animation';
import {constructionStage} from '@/lib/installation';
import {t,nf} from '@/lib/i18n';
import type {ToolMode} from './manual-scene';
export default function ManualPlan({project:p,selected,tool,draft,onGround,onSelect,grid,preview,moveScope='linked'}:{moveScope?:MoveScope;project:Project;selected:string;tool:ToolMode;draft:Item|null;onGround:(x:number,z:number)=>void;onSelect:(id:string)=>void;grid:boolean;preview?:Item[]}){
 const ref=useRef<SVGSVGElement>(null),[hover,setHover]=useState<{x:number;z:number}|null>(null),margin=15,font=Math.max(p.width,p.depth)/80,site=siteSettings(p),coast=portFrame(p),bounds=p.facility==='port'?shoreBounds(p):{minX:-p.width/2,maxX:p.width/2,minZ:-p.depth/2,maxZ:p.depth/2};
 const locate=(e:React.PointerEvent)=>{const svg=ref.current;if(!svg)return null;const pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const ctm=svg.getScreenCTM();if(!ctm)return null;const local=pt.matrixTransform(ctm.inverse());return{x:Math.round(local.x*2)/2,z:Math.round(local.y*2)/2}};
 const footprint=(i:Item,fill:string,stroke:string,dashed=false)=>roundKinds.includes(i.kind)?<circle cx={i.x} cy={i.z} r={i.width/2} fill={fill} stroke={stroke} strokeWidth=".35" strokeDasharray={dashed?'.7 .5':undefined}/>:<polygon points={corners(itemFootprint(i)).map(v=>`${v.x},${v.z}`).join(' ')} fill={fill} stroke={stroke} strokeWidth=".3" strokeDasharray={dashed?'.7 .5':undefined}/>;
 return <div className="manual-plan"><svg ref={ref} viewBox={`${bounds.minX-margin} ${bounds.minZ-margin} ${bounds.maxX-bounds.minX+margin*2} ${bounds.maxZ-bounds.minZ+margin*2}`} aria-label={t(p.language,'plan')} onPointerMove={e=>setHover(locate(e))} onPointerLeave={()=>setHover(null)} onPointerUp={e=>{if(e.button!==0)return;if(tool!=='select'){const point=locate(e);if(point)onGround(point.x,point.z)}}}>
 <defs><pattern id="site-grid" width="5" height="5" patternUnits="userSpaceOnUse"><path d="M 5 0 L 0 0 0 5" fill="none" stroke="#c7d0d6" strokeWidth=".08"/></pattern></defs>
 {p.facility==='port'&&<g transform={`rotate(${-coast.angle*180/Math.PI})`} pointerEvents="none"><rect x={-10000} y={coast.quayEnd} width={20000} height={20000} fill="#80a8b9"/><rect x={-coast.width/2} y={coast.depth/2} width={coast.width} height={coast.quayDepth} fill="#a3afb4"/><rect x={-coast.shipLength/2} y={coast.shipZ-coast.shipBeam/2} width={coast.shipLength} height={coast.shipBeam} rx={coast.shipBeam*.28} fill="#3d5664" stroke="#7695a5" strokeWidth=".4"/>{Array.from({length:coast.hatches},(_,n)=>{const usable=coast.shipLength-coast.shipBeam*1.5,cell=usable/coast.hatches,x=-coast.shipLength/2+coast.shipBeam*.8+(n+.5)*cell;return <rect key={n} x={x-(cell-2)/2} y={coast.shipZ-coast.shipBeam*.33} width={Math.max(2,cell-2)} height={coast.shipBeam*.66} fill="#b59b68" stroke="#e0e7e7" strokeWidth=".5"/>})}</g>}
 <rect x={-p.width/2} y={-p.depth/2} width={p.width} height={p.depth} fill="#ced5d5" stroke="#89949c" strokeWidth=".3"/>
 <rect x={-p.width/2+site.setback} y={-p.depth/2+site.setback} width={Math.max(0,p.width-2*site.setback)} height={Math.max(0,p.depth-2*site.setback)} fill="#e9edef" stroke="#b38c49" strokeDasharray="1 .8" strokeWidth=".2"/>
 {grid&&<rect x={-p.width/2} y={-p.depth/2} width={p.width} height={p.depth} fill="url(#site-grid)"/>}
 {p.items.map((source,n)=>{const state=constructionStage(p.construction,source.id),stage=state.stage;if(source.kind==='walkway'&&stage==='queued')return null;const i=source.kind==='walkway'&&p.construction?.timeline===2?{...source,...walkwayPose(p,source,stage,state.progress)}:source;const queued=stage==='queued',working=!queued&&stage!=='complete';const fill=stage==='excavating'?'#866b4c':queued?'#f1ece2':working?'#ddd1b6':selected===i.id?'#f8d7df':i.kind==='walkway'?'#aabac2':'#fafcfc',stroke=selected===i.id?'#c00031':working||queued?'#b18a35':'#7b8f9a';return <g key={i.id} role="button" tabIndex={0} aria-label={`${handlingName(i,p.language)} ${n+1} · ${t(p.language,stage)}`} onPointerUp={e=>{if(tool==='select'){e.stopPropagation();onSelect(i.id)}}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(i.id)}}} className="plan-item">{isSilo(i)&&footprint({...i,width:i.width+2*site.foundationApron,depth:i.depth+2*site.foundationApron},'#c9ceca',stroke,queued)}{footprint(i,fill,stroke,queued)}{i.kind==='shiploader'&&i.model&&<g pointerEvents="none"><line x1={i.x} y1={i.z} x2={loaderTip(i).x} y2={loaderTip(i).z} stroke={reachesVessel(p,i)?'#31815e':'#c48d34'} strokeWidth=".6"/><circle cx={loaderTip(i).x} cy={loaderTip(i).z} r=".7" fill={reachesVessel(p,i)?'#31815e':'#c48d34'}/></g>}<text x={i.x} y={i.z+font/3} textAnchor="middle" fontSize={font} fill="#435965" pointerEvents="none">{String(n+1).padStart(2,'0')}</text></g>})}
 {elevatorAccessDecks(p.items).filter(i=>!i.id.includes(':head-')).map(i=>{const owner=p.items.find(e=>i.id.startsWith(`access:${e.id}:`)),state=owner?constructionStage(p.construction,owner.id):{stage:'complete'};if(['queued','sitePreparation','baseAnchoring','foundation','frameAssembly'].includes(state.stage))return null;return <g key={i.id} pointerEvents="none">{footprint(i,state.stage==='complete'?'#b0c0c8':'#ddd1b6','#667f8b',state.stage!=='complete')}</g>})}
 {preview?.map((i,n)=><g key={i.id} pointerEvents="none">{footprint({...i,width:i.width+site.foundationApron*2,depth:i.depth+site.foundationApron*2},'#e8ddbe99','#b58b3c',true)}<text x={i.x} y={i.z+font/3} textAnchor="middle" fontSize={font} fill="#977127">{String(n+1).padStart(2,'0')}</text></g>)}
 {hover&&draft&&tool==='move'&&(()=>{const move=movementPreview(p,draft.id,hover.x,hover.z,moveScope);return <g pointerEvents="none">{move.moving.map(i=><g key={i.id}>{footprint(i,move.issue?'#c0003140':'#31815e40',move.issue?'#c00031':'#31815e',true)}</g>)}</g>})()}
 {hover&&draft&&!isSilo(draft)&&tool==='place'&&footprint({...draft,...hover},itemIssue(p,{...draft,...hover})?'#c0003140':'#31815e40',itemIssue(p,{...draft,...hover})?'#c00031':'#31815e')}
 <text x="0" y={-p.depth/2-5} textAnchor="middle" fontSize={font*1.2} fill="#6e818d">{nf(p.language,p.width)} m</text><text x={-p.width/2-5} y="0" textAnchor="middle" transform={`rotate(-90 ${-p.width/2-5} 0)`} fontSize={font*1.2} fill="#6e818d">{nf(p.language,p.depth)} m</text>
 </svg></div>;
}
