'use client';
import {movementPreview,type MoveScope} from '@/lib/movement';
import {shoreBounds} from '@/lib/site-context';
import {updateWater} from '@/lib/port-model';
import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {environment,manualItem} from '@/lib/manual-models';
import {disposeModel} from '@/lib/models';
import {itemBottom,itemFootprint,itemIssue,itemTop,type Item,type Project} from '@/lib/editor';
import {t} from '@/lib/i18n';
import {siteGrid} from '@/lib/site-grid';
import {constructionVisuals} from '@/lib/construction-models';
import {siteSettings} from '@/lib/editor';
export type ToolMode='select'|'place'|'move';
export default function ManualScene({project,selected,tool,draft,onGround,onSelect,reset,grid,preview,moveScope='linked'}:{moveScope?:MoveScope;preview?:Item[];project:Project;selected:string;tool:ToolMode;draft:Item|null;onGround:(x:number,z:number)=>void;onSelect:(id:string)=>void;reset:number;grid:boolean}){
 const hostRef=useRef<HTMLDivElement>(null),runtime=useRef<{scene:T.Scene;items:T.Group;grid:T.Group;preview:T.Group;terrain:T.Group;selection:T.Group;update?:(elapsed:number)=>void}|null>(null),live=useRef({project,tool,draft,onGround,onSelect,moveScope});live.current={project,tool,draft,onGround,onSelect,moveScope};const [error,setError]=useState(false);const portKey=JSON.stringify(project.port),siteKey=JSON.stringify(siteSettings(project)),buildKey=JSON.stringify([project.construction?.siloIds,project.construction?.walkwayIds,project.construction?.equipmentJobs,project.items.filter(i=>i.kind==='intake').map(i=>[i.id,i.x,i.z,i.rotation,i.width,i.depth,i.y])]);
 useEffect(()=>{const host=hostRef.current;if(!host)return;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true})}catch{setError(true);return}
  renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xeef1f3);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;host.appendChild(renderer.domElement);
  const scene=new T.Scene();scene.add(new T.HemisphereLight(0xf4f9ff,0x697983,3));const light=new T.DirectionalLight(0xfff7ee,3);light.position.set(-50,120,60);light.castShadow=true;light.shadow.mapSize.set(2048,2048);const span=Math.max(project.width,project.depth);Object.assign(light.shadow.camera,{left:-span,right:span,top:span,bottom:-span,far:1000});light.shadow.bias=-.001;scene.add(light);
  const terrain=new T.Group();terrain.add(environment(project));scene.add(terrain);const items=new T.Group();scene.add(items);const selection=new T.Group();scene.add(selection);const gridHelper=new T.Group();scene.add(gridHelper);
  const edges=new T.BufferGeometry().setFromPoints([new T.Vector3(-project.width/2,.04,-project.depth/2),new T.Vector3(project.width/2,.04,-project.depth/2),new T.Vector3(project.width/2,.04,project.depth/2),new T.Vector3(-project.width/2,.04,project.depth/2),new T.Vector3(-project.width/2,.04,-project.depth/2)]);scene.add(new T.Line(edges,new T.LineBasicMaterial({color:0x8a929c})));
  const camera=new T.OrthographicCamera(-80,80,60,-60,.1,5000);camera.position.set(span*.8,span*.85,span*1.08);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,2,project.facility==='port'?project.depth*.08:0);controls.enableDamping=true;controls.maxPolarAngle=Math.PI/2.1;controls.minZoom=.3;controls.maxZoom=10;
  const ghost=new T.Mesh(new T.BoxGeometry(1,1,1),new T.MeshBasicMaterial({color:0xc00031,transparent:true,opacity:.22,depthWrite:false}));ghost.visible=false;scene.add(ghost);const groundGhost=new T.Mesh(new T.BoxGeometry(1,.06,1),new T.MeshBasicMaterial({color:0x398875,transparent:true,opacity:.35,depthWrite:false}));groundGhost.visible=false;scene.add(groundGhost);const moveGhosts=new T.Group(),moveGeo=new T.BoxGeometry(1,.07,1),moveMat=new T.MeshBasicMaterial({transparent:true,opacity:.2,depthWrite:false});scene.add(moveGhosts);
  const previewGroup=new T.Group();scene.add(previewGroup);runtime.current={scene,items,grid:gridHelper,preview:previewGroup,terrain,selection};const resize=()=>{
   const width=host.clientWidth,height=host.clientHeight;if(!width||!height)return;
   renderer.setSize(width,height);const aspect=width/height;
   const top=Math.max(24,...live.current.project.items.map(itemTop))+(live.current.project.construction?.equipmentJobs?.length?30:live.current.project.construction?.walkwayIds.length?12:0),portExtra=project.facility==='port'?28:16;
   const frameBounds=project.facility==='port'?shoreBounds(project):{minX:-project.width/2,maxX:project.width/2,minZ:-project.depth/2,maxZ:project.depth/2+portExtra};
   controls.target.set((frameBounds.minX+frameBounds.maxX)/2,top*.25,(frameBounds.minZ+frameBounds.maxZ)/2);
   const direction=new T.Vector3(1,1,1).normalize(),right=new T.Vector3().crossVectors(new T.Vector3(0,1,0),direction).normalize(),up=new T.Vector3().crossVectors(direction,right);
   let halfWidth=0,halfHeight=0;
   const bounds=project.facility==='port'?shoreBounds(project):{minX:-project.width/2,maxX:project.width/2,minZ:-project.depth/2,maxZ:project.depth/2+portExtra};
   for(const x of [bounds.minX,bounds.maxX])for(const y of [0,top])for(const z of [bounds.minZ,bounds.maxZ]){
    const v=new T.Vector3(x,y,z).sub(controls.target);halfWidth=Math.max(halfWidth,Math.abs(v.dot(right)));halfHeight=Math.max(halfHeight,Math.abs(v.dot(up)));
   }
   const half=Math.max(halfHeight,halfWidth/aspect)*1.12;camera.left=-half*aspect;camera.right=half*aspect;camera.top=half;camera.bottom=-half;camera.zoom=1;camera.updateProjectionMatrix();
   camera.position.copy(controls.target).addScaledVector(direction,span*3);controls.update();
  };const observer=new ResizeObserver(resize);observer.observe(host);resize();
  const ray=new T.Raycaster(),plane=new T.Plane(new T.Vector3(0,1,0),0),point=new T.Vector3();let down={x:0,y:0};
  const locate=(e:PointerEvent)=>{const b=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1),camera);return ray.ray.intersectPlane(plane,point)?{x:Math.round(point.x*2)/2,z:Math.round(point.z*2)/2}:null};
  const move=(e:PointerEvent)=>{const p=locate(e),d=live.current.draft;ghost.visible=!!p&&!!d&&live.current.tool!=='select'&&(live.current.tool==='move'||!['flat','economic','commercial','industrial','square','feed','temporary'].includes(d.kind));if(p&&d&&ghost.visible){const next={...d,...p};const foot=itemFootprint(d),height=d.height+(d.rise||0),angle=d.rotation*Math.PI/180,offset=d.kind==='shiploader'&&d.model?d.width/2:0;ghost.scale.set(d.width,height,d.depth);ghost.position.set(p.x+Math.cos(angle)*offset,itemBottom(d)+height/2,p.z-Math.sin(angle)*offset);ghost.rotation.y=angle;groundGhost.scale.set(foot.width,1,foot.depth);groundGhost.position.set(p.x,.05,p.z);groundGhost.rotation.y=angle;const moved=live.current.tool==='move'?movementPreview(live.current.project,d.id,p.x,p.z,live.current.moveScope):null;const color=(moved?moved.issue:itemIssue(live.current.project,next))?0xc00031:0x398875;moveMat.color.set(color);moveGhosts.visible=!!moved;if(moved){while(moveGhosts.children.length<moved.moving.length)moveGhosts.add(new T.Mesh(moveGeo,moveMat));moveGhosts.children.forEach((o,n)=>{const i=moved.moving[n];o.visible=!!i;if(!i)return;const foot=itemFootprint(i);o.position.set(i.x,.06,i.z);o.scale.set(foot.width,1,foot.depth);o.rotation.y=i.rotation*Math.PI/180})}(ghost.material as T.MeshBasicMaterial).color.set(color);(groundGhost.material as T.MeshBasicMaterial).color.set(color)}groundGhost.visible=ghost.visible;if(!ghost.visible)moveGhosts.visible=false};
  const start=(e:PointerEvent)=>{down={x:e.clientX,y:e.clientY}};const click=(e:PointerEvent)=>{if(e.button!==0)return;if(Math.hypot(down.x-e.clientX,down.y-e.clientY)>5)return;const p=locate(e);if(!p)return;if(live.current.tool!=='select'){live.current.onGround(p.x,p.z);return}const hit=ray.intersectObjects(items.children,true).find(hit=>{let o:T.Object3D|null=hit.object;while(o){if(!o.visible)return false;o=o.parent}return true});let node=hit?.object;while(node&&!node.userData.id)node=node.parent!;live.current.onSelect(node?.userData.id||'')};const leave=()=>{ghost.visible=false;groundGhost.visible=false;moveGhosts.visible=false};
  renderer.domElement.addEventListener('pointerdown',start);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',click);renderer.domElement.addEventListener('pointerleave',leave);
  let observed=-1,observedAt=0;renderer.setAnimationLoop(()=>{const c=live.current.project.construction,now=performance.now();if(c?.elapsed!==observed){observed=c?.elapsed||0;observedAt=now}runtime.current?.update?.(c?c.elapsed+(c.paused?0:Math.min(.35,(now-observedAt)/1000)*c.speed):0);if(live.current.tool==='select'){ghost.visible=false;groundGhost.visible=false;moveGhosts.visible=false}updateWater(terrain,now/1000);controls.update();renderer.render(scene,camera)});
  return()=>{renderer.setAnimationLoop(null);observer.disconnect();controls.dispose();disposeModel(scene);renderer.dispose();renderer.domElement.remove();runtime.current=null};
 },[project.width,project.depth,project.facility,reset,siteKey,portKey]);
 useEffect(()=>{const r=runtime.current;if(!r)return;disposeModel(r.terrain);r.terrain.clear();r.terrain.add(environment(project))},[project.items,project.construction?.siloIds,project.width,project.depth,project.facility,siteKey,portKey,reset]);
 useEffect(()=>{const r=runtime.current;if(!r)return;disposeModel(r.items);r.items.clear();const visuals=constructionVisuals(project,'');r.items.add(visuals.root);r.update=visuals.update;r.update(project.construction?.elapsed||0);disposeModel(r.grid);r.grid.clear();r.grid.add(siteGrid(project));r.grid.visible=grid},[project.items,grid,project.width,project.depth,project.facility,reset,siteKey,portKey,buildKey]);
 useEffect(()=>{const r=runtime.current;if(!r)return;disposeModel(r.selection);r.selection.clear();const i=project.items.find(i=>i.id===selected);if(!i)return;const a=i.rotation*Math.PI/180,offset=i.kind==='shiploader'&&i.model?i.width/2:0,top=itemTop(i),helper=new T.LineSegments(new T.EdgesGeometry(new T.BoxGeometry(i.width,Math.max(.1,top-itemBottom(i)),i.depth)),new T.LineBasicMaterial({color:0xc00031}));helper.position.set(i.x+Math.cos(a)*offset,itemBottom(i)+(top-itemBottom(i))/2,i.z-Math.sin(a)*offset);helper.rotation.y=a;r.selection.add(helper)},[selected,project.items,project.width,project.depth,project.facility,reset,siteKey,portKey]);
 useEffect(()=>{const r=runtime.current;if(!r)return;disposeModel(r.preview);r.preview.clear();for(const i of preview||[]){const radius=i.width/2+siteSettings(project).foundationApron;const shape=i.kind==='square'?new T.EdgesGeometry(new T.BoxGeometry(i.width+1.2,.03,i.depth+1.2)):new T.EdgesGeometry(new T.CylinderGeometry(radius,radius,.03,64,1,true));const line=new T.LineSegments(shape,new T.LineBasicMaterial({color:0xc3984b,transparent:true,opacity:.85}));line.position.set(i.x,.06,i.z);r.preview.add(line)}},[preview,siteKey,portKey,reset,buildKey,project.width,project.depth,project.facility]);
 return <div className="manual-canvas" ref={hostRef}>{error&&<div className="canvas-alert">{t(project.language,'webgl')}</div>}</div>;
}
