'use client';
import type {Setup,Project} from '@/lib/editor';
import {portSettings,designBasis,type PortSettings,type DesignBasis} from '@/lib/site-context';
import {missingDesignInputs,roofSnowForce} from '@/lib/design-review';
import {t,nf,type Lang,type TextKey} from '@/lib/i18n';
export function SiteFields({value,onChange,lang,locked=true}:{value:Setup;onChange:(next:Setup)=>void;lang:Lang;locked?:boolean}){const port=portSettings(value),design=designBasis(value);return <div className="site-options">
 {value.facility==='port'&&<details open><summary>{t(lang,'portLayout')}</summary><div className="customer-grid"><label className="m-field"><span>{t(lang,'coastEdge')}</span><select className="m-input" value={port.edge} onChange={e=>onChange({...value,port:{...port,edge:e.target.value as PortSettings['edge']}})}>{(['south','north','east','west'] as const).map(k=><option value={k} key={k}>{t(lang,k)}</option>)}</select></label>{(['quayDepth','shipGap','shipBeam','shipLength','hatches'] as const).map(k=><label className="m-field" key={k}><span>{t(lang,k)}{k==='hatches'?'':' (m)'}</span><input className="m-input" type="number" step={k==='hatches'?1:.5} min={{quayDepth:8,shipGap:1,shipBeam:8,shipLength:30,hatches:1}[k]} max={{quayDepth:60,shipGap:30,shipBeam:60,shipLength:350,hatches:10}[k]} value={port[k]} onChange={e=>onChange({...value,port:{...port,[k]:Number(e.target.value)}})}/></label>)}</div></details>}
 <details><summary>{t(lang,'designBasis')}{locked?' · 🔒':''}</summary><fieldset disabled={locked}><div className="customer-grid">{(['location','standard'] as const).map(k=><label className="m-field" key={k}><span>{t(lang,k==='standard'?'designStandard':'location')}</span><input className="m-input" maxLength={160} value={design[k]} placeholder={t(lang,'unknown')} onChange={e=>onChange({...value,design:{...design,[k]:e.target.value}})}/></label>)}{(['snowLoad','windSpeed','seismicPga','soilBearing','throughput'] as const).map(k=><label className="m-field" key={k}><span>{t(lang,k)} ({{snowLoad:'kN/m²',windSpeed:'m/s',seismicPga:'g',soilBearing:'kPa',throughput:'t/h'}[k]})</span><input className="m-input" type="number" step="any" min="0" max={{snowLoad:30,windSpeed:150,seismicPga:3,soilBearing:10000,throughput:10000}[k]} value={design[k]??''} placeholder={t(lang,'unknown')} onChange={e=>onChange({...value,design:{...design,[k]:e.target.value===''?null:Number(e.target.value)}})}/></label>)}<label className="m-field"><span>{t(lang,'corrosion')}</span><select className="m-input" value={design.corrosion} onChange={e=>onChange({...value,design:{...design,corrosion:e.target.value as DesignBasis['corrosion']}})}>{['unknown','C2','C3','C4','C5','CX'].map(k=><option key={k} value={k}>{k==='unknown'?t(lang,'unknown'):k}</option>)}</select></label></div><p className="linked-note">{t(lang,'designNote')}</p></fieldset></details>
 </div>}
export function DesignSummary({project:p}:{project:Project}){const missing=missingDesignInputs(p),snow=roofSnowForce(p),d=designBasis(p);return <details className="design-summary"><summary>{t(p.language,'designBasis')} <span>{7-missing.length}/7</span></summary><p>{d.location||t(p.language,'unknown')}</p>{missing.length>0&&<p className="linked-note">{t(p.language,'siteInputsMissing')}</p>}{snow!==null&&<p>{t(p.language,'roofSnowTotal')}: <b>{nf(p.language,snow,1)} kN</b></p>}{p.facility==='port'&&<p className="linked-note">{t(p.language,'marineReview')}</p>}<small>{t(p.language,'designNote')}</small><a href="/research#liman-tasima" target="_blank" rel="noreferrer">{t(p.language,'source')} ↗</a></details>}
