import {portSources} from './port-research';
export const sources = [
 {id:1,publisher:'Mysilo',title:'Flat Bottom Silos',date:'Tarih belirtilmemiş',url:'https://www.mysilo.com/en/category/17/flat-bottom-silos'},
 {id:2,publisher:'Mysilo',title:'Flat Bottom Silo – Capacity Chart',date:'Belgede tarih doğrulanamadı',url:'https://www.mysilo.com/upload/ckfinder/files/capacity/mysilo-flat-bottom-silo-capacity-chart-en.pdf'},
 {id:3,publisher:'Mysilo',title:'Flat Bottom Silo Capacities – 800 kg/m³',date:'Belgede tarih doğrulanamadı',url:'https://www.mysilo.com/dosyalar/kapasite-tablolari/mysilo-flat-bottom-silo-capacities-table-800.pdf'},
 {id:4,publisher:'University of Minnesota Extension',title:'Drying wheat and barley',date:'Tarih belirtilmemiş',url:'https://extension.umn.edu/agriculture/crop-production/small-grains/drying-wheat-and-barley'},
 {id:5,publisher:'University of Minnesota Extension',title:'Storing wheat and barley',date:'Tarih belirtilmemiş',url:'https://extension.umn.edu/agriculture/crop-production/small-grains/storing-wheat-and-barley'},
 {id:6,publisher:'University of Minnesota Extension',title:'Proper Spring Grain Drying and Storage Critical',date:'Mart 2024',url:'https://blog-crop-news.extension.umn.edu/2024/03/proper-spring-grain-drying-and-storage.html'},
 {id:7,publisher:'Cimbria',title:'Delta 145 Pre-cleaner – Data Sheet',date:'Haziran 2023',url:'https://www.cimbria.com/content/dam/public/grain-and-protein/cimbria/data-sheets/screen-cleaner/140/Pre_Cleaner_145_Datasheet_EN.pdf'},
 {id:8,publisher:'Cimbria',title:'Continuous Flow Dryer – Brochure',date:'Belgede tarih doğrulanamadı',url:'https://www.cimbria.com/content/dam/public/grain-and-protein/cimbria/brochures/drying/continuous-flow-dryer/Continuous_Flow_Dryer_GB.pdf'},
 {id:9,publisher:'Cimbria',title:'Dryer Column – Data Sheet',date:'Ekim 2024',url:'https://www.cimbria.com/content/dam/public/grain-and-protein/cimbria/data-sheets/continuous-flow-dryers/a-b-c-d-e-dryers-eco-master/Dryer_Column_Datasheet_EN.pdf'},
 {id:10,publisher:'Silos Córdoba',title:'Heavy Duty Chain Conveyor',date:'Tarih belirtilmemiş',url:'https://www.siloscordoba.com/products/handling-equipment/heavy-duty-range/chain-conveyor/'},
 {id:11,publisher:'Silos Córdoba',title:'Handling Equipment – Industrial Range',date:'Dosya yolu 2024/09; belge tarihi doğrulanamadı',url:'https://www.siloscordoba.com/wp-content/uploads/2024/09/02.Handling-Equipment-En-V1.pdf'},
 {id:12,publisher:'Cimbria',title:'Intake Systems',date:'Tarih belirtilmemiş',url:'https://www.cimbria.com/en/products/conveying/intake-systems/'},
 {id:13,publisher:'Brock Grain',title:'5 Key Points for a Strong Bin Foundation',date:'25 Ekim 2022',url:'https://www.brockgrain.com/blog/5-key-points-for-a-strong-bin-foundation/'},
 {id:14,publisher:'Brock Grain',title:'Grain System Management – Bin Inspections and Maintenance, MCB2040B',date:'Belgede yayın tarihi doğrulanamadı',url:'https://blog.brockgrain.com/wp-content/uploads/2025/07/Storage-Bin-Maintenance-MCB2040B.pdf'},
 {id:15,publisher:'Mysilo',title:'After-Sales Service',date:'Tarih belirtilmemiş',url:'https://mysilo.com/en/page/After-Sales-Service'},
 {id:16,publisher:'OSHA',title:'29 CFR 1910.272 – Grain handling facilities',date:'Güncel web metni; ABD',url:'https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.272'},
 {id:17,publisher:'T.C. Ticaret Bakanlığı',title:'Lisanslı Depoculuk Mevzuatı',date:'Sayfa tarihi 17 Nisan 2026',url:'https://www.ticaret.gov.tr/ic-ticaret/mevzuat/lisansli-depoculuk'},
 {id:18,publisher:'T.C. Ticaret Bakanlığı',title:'Lisanslı Depoculuk Denetim / İnceleme Süreçleri',date:'Erişim 14 Eylül 2026',url:'https://www.ticaret.gov.tr/ic-ticaret/lisansli-depoculuk/lisansli-depoculuk-denetim-inceleme-surecleri'},
 {id:19,publisher:'European Commission JRC',title:'Eurocodes – second generation and national parameters',date:'Güncel web sayfası',url:'https://eurocodes.jrc.ec.europa.eu/'},
 {id:20,publisher:'AFAD',title:'Türkiye Bina Deprem Yönetmeliği – Broşür',date:'2018 yönetmeliği; 1 Ocak 2019 yürürlük bilgisi',url:'https://www.afad.gov.tr/kurumlar/afad.gov.tr/39505/xfiles/yonetmelik_brosur.pdf'},
 {id:21,publisher:'OBIAL',title:'Düz Taban Silolar',date:'Tarih belirtilmemiş',url:'https://obial.com.tr/urunler/dtsilo'},
 {id:22,publisher:'Sketchfab / juninholiveira',title:'Grain Silo – 3D model',date:'10 Şubat 2016',url:'https://sketchfab.com/3d-models/grain-silo-395938614968466394a45456cbd188f6'},
 {id:23,publisher:'Sketchfab',title:'Download API Guidelines',date:'Güncel geliştirici rehberi',url:'https://sketchfab.com/developers/download-api/guidelines'},
 {id:24,publisher:'Three.js',title:'GLTFExporter',date:'Güncel dokümantasyon',url:'https://threejs.org/docs/pages/GLTFExporter.html'},
 {id:25,publisher:'Mysilo',title:'Silo Equipments',date:'Tarih belirtilmemiş',url:'https://mysilo.com/en/category/222/silo-equipments'},
 {id:26,publisher:'Brock Grain',title:'On-Farm Grain Bins',date:'Tarih belirtilmemiş',url:'https://www.brockgrain.com/brock-product/on-farm-grain-bins/'},
 {id:27,publisher:'T.C. Çalışma ve Sosyal Güvenlik Bakanlığı',title:'Tarımda Güvenlik ve Sağlık',date:'Belgede tarih doğrulanamadı',url:'https://www.csgb.gov.tr/Media/sy1d1aul/tar%C4%B1mda-guevenlik-ve-sa%C4%9Fl%C4%B1k.pdf'},
 ...portSources,
];
export const assets = [
 {id:'flat-bin',title:'Düz tabanlı silo',english:'Flat-bottom grain bin',category:'Depolama',description:'Uzun süreli ana stok. Silindirik gövde, konik çatı, çevresel kuşaklar, merdiven ve fan.',dimensions:'Ø 12,83 m · gövde 10,14 m',source:1},
 {id:'hopper-bin',title:'Konik tabanlı silo',english:'Hopper-bottom silo',category:'Depolama',description:'Parti geçişleri ve boşaltma için ayaklı, konik alt gövdeli stok. Akış rejimi bu modelde hesaplanmaz.',dimensions:'Ø 8,25 m · gövde 6,76 m',source:25},
 {id:'elevator',title:'Kovalı elevatör',english:'Bucket elevator / grain leg',category:'Taşıma',description:'Tahılı dikey taşır. İki gövde, taşıyıcı kule ve tahrik başlığı; üst dağıtım hattına bağlanır.',dimensions:'3 × 3 m · yükseklik 24 m',source:11},
 {id:'dryer',title:'Kurutma kulesi',english:'Continuous-flow grain dryer',category:'Şartlandırma',description:'Kademeli modüler gövde ve fanlar. Gösterilen ebatlar temsilidir; debiden marka/model seçimi yapılmaz.',dimensions:'7 × 9 m · yükseklik ≈ 18 m',source:8},
 {id:'cleaner',title:'Ön temizleyici',english:'Grain pre-cleaner',category:'Şartlandırma',description:'Kaba yabancı madde ve hafif fraksiyon ayrımı için temsili ekipman. Aspirasyon ayrıca projelendirilir.',dimensions:'5 × 5 m rezerv alan',source:7},
 {id:'intake',title:'Alım çukuru',english:'Receiving pit',category:'Kabul',description:'Araç boşaltma ızgarası ve sundurma. Taşıt yükü, yeraltı hacmi ve drenaj hesabı içermez.',dimensions:'12 × 5 m nominal taban',source:12},
 {id:'wetbin',title:'Yaş ürün tamponu',english:'Wet holding bin',category:'Depolama',description:'Kabul ile kurutma arasındaki kısa süreli tampon. Ana depolama kapasitesine eklenmez.',dimensions:'Ø 6 m · gövde 5 m',source:8},
 {id:'office',title:'Kontrol binası',english:'Control room',category:'Yardımcı',description:'Otomasyon ve operasyon için temsili hacim. Laboratuvar ve personel yerleşimi sonraki tasarım aşamasıdır.',dimensions:'9 × 6 m · yükseklik 3,5 m',source:15},
];
