import type {Location,LoadSnapshot} from './business';
import {SITE_EQUIPMENT} from './site-equipment-catalog';
import {validHandling,type HandlingModel} from './handling-catalog';
import {DEFAULT_PORT,validPort,validDesign,portFrame,toCoast,type PortSettings,type DesignBasis} from './site-context';
import {CURRENCIES,LANGUAGES,type Currency,type Lang,type TextKey} from './i18n';
import {GRAINS,plan,binVolume} from './planner';
import {decodeProject} from './project';
export const SILO_KINDS=['flat','economic','commercial','industrial','square','feed','temporary'] as const;
export const KINDS=[...SILO_KINDS,'elevator','walkway','building','tower','conveyor','intake','dryer','cleaner','shiploader'] as const;
export type Kind=typeof KINDS[number];
export const EQUIPMENT_KINDS=['elevator','building','tower','conveyor','intake','dryer','cleaner','shiploader'] as const;
export type EquipmentKind=typeof EQUIPMENT_KINDS[number];
export type EquipmentJob={id:string;kind:EquipmentKind;mode:'install'|'access'};
export type Grain=typeof GRAINS[number]['id']|'animalFeed';
export type SiteSettings={setback:number;siloGap:number;foundationApron:number;walkwayOverhang:number};
export type Construction={equipmentJobs?:EquipmentJob[];timeline?:2;aerationIds?:string[];elapsed:number;paused:boolean;speed:1|2|4|6|8;siloIds:string[];walkwayIds:string[]};
export const DEFAULT_SITE:SiteSettings={setback:5,siloGap:3,foundationApron:.6,walkwayOverhang:2};
export type Item={model?:HandlingModel;rise?:number;access?:{walkwayIds:string[]};layout?:{group:string;row:number;column:number};anchor?:{siloIds:string[];axis:'x'|'z'};id:string;kind:Kind;x:number;z:number;y:number;rotation:number;width:number;depth:number;height:number};
export type Customer={firstName:string;lastName:string;company:string;email:string;phone:string;country:string;address:string};
export type Project={location?:Location;loadProfile?:LoadSnapshot;version:2;id:string;name:string;grain:Grain;density:number;target:number;facility:'inland'|'port';width:number;depth:number;preferredSilo:typeof SILO_KINDS[number];language:Lang;currency:Currency;createdAt:string;updatedAt:string;items:Item[];port?:PortSettings;design?:DesignBasis;site?:SiteSettings;construction?:Construction;customer?:Customer};
export type Setup=Omit<Project,'version'|'id'|'items'|'createdAt'|'updatedAt'|'customer'|'construction'>;
export const PROJECTS_KEY='mysilo:projects:v2';
export const PREFS_KEY='mysilo:preferences:v2';
export const grainIds=[...GRAINS.map(g=>g.id),'animalFeed'];
export const roundKinds=['flat','economic','commercial','industrial','feed','temporary'];
const root='https://www.mysilo.com';
export const PRODUCTS:Record<Kind,{width:number;depth:number;height:number;y:number;image:string;source:string;family:'storage'|'equipment'}>={
 flat:{width:11,depth:11,height:12,y:0,image:'flat.png',source:root+'/tr/category/16/tahil-depolama-silolari',family:'storage'},
 economic:{width:6.41,depth:6.41,height:6.76,y:0,image:'economic.png',source:root+'/tr/category/349/Konik-Silolar',family:'storage'},
 commercial:{width:9.16,depth:9.16,height:10.14,y:0,image:'commercial.png',source:root+'/tr/category/349/Konik-Silolar',family:'storage'},
 industrial:{width:14.66,depth:14.66,height:18,y:0,image:'industrial.png',source:root+'/tr/category/16/tahil-depolama-silolari',family:'storage'},
 square:{width:8,depth:8,height:12,y:0,image:'square.svg',source:root+'/tr/category/355/Kare-Silolar',family:'storage'},
 feed:{width:3,depth:3,height:5,y:0,image:'feed.png',source:root+'/tr/category/435/Yem-silosu',family:'storage'},
 temporary:{width:24,depth:24,height:3,y:0,image:'temporary.png',source:root+'/tr/category/450/Gecici-Tahil-Depolama',family:'storage'},
 elevator:{width:3,depth:3,height:24,y:0,image:'elevator.svg',source:root+'/tr/category/33/tahil-tasima-makineleri',family:'equipment'},
 walkway:{width:16,depth:1.8,height:1.2,y:18,image:'walkway.png',source:root+'/tr/category/74/Yurume-Yolu',family:'equipment'},
 building:{width:12,depth:9,height:8,y:0,image:'building.png',source:SITE_EQUIPMENT.building.source,family:'equipment'},
 tower:{width:4,depth:4,height:18,y:0,image:'tower.png',source:SITE_EQUIPMENT.tower.source,family:'equipment'},
 conveyor:{width:18,depth:1.2,height:1,y:19,image:'conveyor.svg',source:root+'/tr/category/33/tahil-tasima-makineleri',family:'equipment'},
 intake:{width:4,depth:4,height:3.2,y:0,image:'intake.png',source:SITE_EQUIPMENT.intake.source,family:'equipment'},
 dryer:{width:7,depth:9,height:17,y:0,image:'dryer.jpeg',source:SITE_EQUIPMENT.dryer.source,family:'equipment'},
 cleaner:{width:5,depth:5,height:6,y:0,image:'cleaner.png',source:SITE_EQUIPMENT.cleaner.source,family:'equipment'},
 shiploader:{width:24,depth:5,height:17,y:0,image:'shiploader.png',source:root+'/tr/category/33/tahil-tasima-makineleri',family:'equipment'},
};
export function createItem(kind:Kind,x=0,z=0):Item{const p=PRODUCTS[kind];return{id:crypto.randomUUID(),kind,x,z,y:p.y,rotation:0,width:p.width,depth:p.depth,height:p.height}}
export function itemBottom(i:Item){return i.kind==='intake'?i.y+.12-i.height:i.y}
export function itemTop(i:Item){if(i.kind==='intake')return i.y+.12;if(['economic','commercial','feed'].includes(i.kind))return i.y+i.height+i.width/2+2.5+i.width/2*Math.tan(28*Math.PI/180);if(['flat','industrial'].includes(i.kind))return i.y+i.height+.4+i.width/2*Math.tan(28*Math.PI/180);if(i.kind==='temporary')return i.y+i.height+i.width/2*.3;return i.y+i.height+(i.kind==='conveyor'?(i.rise||0):0)}
export function itemCapacity(i:Item,density:number){if(!SILO_KINDS.includes(i.kind as typeof SILO_KINDS[number]))return 0;if(i.kind==='square')return i.width*i.depth*i.height*.95*density/1000;if(i.kind==='temporary'){const r=i.width/2;return(Math.PI*r*r*i.height+Math.PI*r*r*(r*.3)/3)*.95*density/1000}return binVolume(i.width,i.height,['economic','commercial','feed'].includes(i.kind)?'hopper':'flat')*density/1000}
export function corners(i:Item){const a=i.rotation*Math.PI/180,c=Math.cos(a),s=Math.sin(a);return[[-i.width/2,-i.depth/2],[i.width/2,-i.depth/2],[i.width/2,i.depth/2],[-i.width/2,i.depth/2]].map(([x,z])=>({x:i.x+x*c+z*s,z:i.z-x*s+z*c}))}
function overlaps(a:Item,b:Item){
 if(itemTop(a)<=itemBottom(b)+.01||itemTop(b)<=itemBottom(a)+.01)return false;
 const ap=corners(a),bp=corners(b);
 for(const shape of [ap,bp])for(let j=0;j<4;j++){const dx=shape[(j+1)%4].x-shape[j].x,dz=shape[(j+1)%4].z-shape[j].z;const proj=(p:{x:number;z:number})=>-dz*p.x+dx*p.z;const av=ap.map(proj),bv=bp.map(proj);if(Math.max(...av)<=Math.min(...bv)+.01||Math.max(...bv)<=Math.min(...av)+.01)return false}return true;
}
export function siteSettings(p:{site?:SiteSettings}){return p.site||DEFAULT_SITE}
export function isSilo(i:Item){return SILO_KINDS.includes(i.kind as typeof SILO_KINDS[number])}
export function itemIssue(p:Pick<Project,'width'|'depth'|'items'|'site'> & Partial<Pick<Project,'facility'|'port'>>,i:Item,exclude=i.id):TextKey|null{
 const site=siteSettings(p),walk=i.kind==='walkway',extra=walk?site.walkwayOverhang:-site.setback;
 const footprint=isSilo(i)?{...i,width:i.width+2*site.foundationApron,depth:i.depth+2*site.foundationApron}:itemFootprint(i);
 if(p.facility==='port'&&(i.kind==='conveyor'||i.kind==='shiploader')){const coast=portFrame(p),points=corners(footprint).map(pt=>toCoast(p,pt));if(points.some(pt=>Math.abs(pt.x)>coast.width/2-1||pt.z < -coast.depth/2+site.setback||pt.z>coast.quayEnd-1))return'outside';if(i.kind==='shiploader'&&i.model&&points.some(pt=>pt.z<coast.depth/2+1))return'quayOnly'}
 else if(corners(footprint).some(c=>Math.abs(c.x)>p.width/2+extra+.001||Math.abs(c.z)>p.depth/2+extra+.001))return'outside';
 if(p.items.some(other=>{if(other.id===exclude||walk&&other.kind==='walkway'&&i.anchor&&other.anchor)return false;const both=isSilo(i)&&isSilo(other);return overlaps({...footprint,width:footprint.width+(both?site.siloGap:0),depth:footprint.depth+(both?site.siloGap:0)},isSilo(other)?{...other,width:other.width+2*site.foundationApron+(both?site.siloGap:0),depth:other.depth+2*site.foundationApron+(both?site.siloGap:0)}:itemFootprint(other))}))return'overlap';return null;
}
export function itemFootprint(i:Item):Item{return i.kind==='shiploader'&&i.model?{...i,width:i.model==='mobile-telescopic'?5:6.7,depth:Math.max(i.depth,i.model==='mobile-telescopic'?.8*i.depth+.5:.84*i.depth+.65)}:i}
export function validSite(s:SiteSettings){return s&&['setback','siloGap','foundationApron','walkwayOverhang'].every(k=>typeof s[k as keyof SiteSettings]==='number'&&Number.isFinite(s[k as keyof SiteSettings]))&&s.setback>=0&&s.setback<=30&&s.siloGap>=1&&s.siloGap<=30&&s.foundationApron>=.3&&s.foundationApron<=3&&s.walkwayOverhang>=0&&s.walkwayOverhang<=5}
export function validItem(i:Item){return i&&typeof i.id==='string'&&i.id.length>0&&i.id.length<100&&KINDS.includes(i.kind)&&validHandling(i)&&['x','z','y','rotation','width','depth','height'].every(k=>typeof i[k as keyof Item]==='number'&&Number.isFinite(i[k as keyof Item]))&&Math.abs(i.x)<=1000&&Math.abs(i.z)<=1000&&i.y>=0&&i.y<=60&&i.width>=1&&i.width<=(i.kind==='walkway'?650:80)&&i.depth>=.5&&i.depth<=80&&i.height>=.5&&i.height<=60&&Math.abs(i.rotation)<=360&&(roundKinds.includes(i.kind)?i.width===i.depth:true)&&(!i.layout||(typeof i.layout.group==='string'&&i.layout.group.length<100&&Number.isInteger(i.layout.row)&&i.layout.row>=0&&Number.isInteger(i.layout.column)&&i.layout.column>=0))&&(!i.access||(i.kind==='elevator'&&Array.isArray(i.access.walkwayIds)&&i.access.walkwayIds.length>0&&i.access.walkwayIds.length<=2&&new Set(i.access.walkwayIds).size===i.access.walkwayIds.length&&i.access.walkwayIds.every(id=>typeof id==='string'&&id.length>0&&id.length<100)))&&(!i.anchor||(i.kind==='walkway'&&['x','z'].includes(i.anchor.axis)&&Array.isArray(i.anchor.siloIds)&&i.anchor.siloIds.length<=150&&i.anchor.siloIds.every(id=>typeof id==='string'&&id.length<100)))}
export function validSetup(s:Setup){return s&&typeof s.name==='string'&&s.name.trim().length>0&&s.name.length<=100&&grainIds.includes(s.grain)&&['inland','port'].includes(s.facility)&&SILO_KINDS.includes(s.preferredSilo)&&LANGUAGES.some(l=>l.id===s.language)&&CURRENCIES.includes(s.currency)&&['width','depth','density','target'].every(k=>typeof s[k as keyof Setup]==='number'&&Number.isFinite(s[k as keyof Setup]))&&s.width>=20&&s.width<=600&&s.depth>=20&&s.depth<=600&&s.density>=200&&s.density<=1000&&s.target>=0&&s.target<=100000&&(!s.site||validSite(s.site))&&(!s.port||validPort(s.port))&&(!s.design||validDesign(s.design))}
export const emptyCustomer:Customer={firstName:'',lastName:'',company:'',email:'',phone:'',country:'',address:''};
export function validCustomer(c:Customer){return c&&Object.keys(emptyCustomer).every(k=>typeof c[k as keyof Customer]==='string'&&c[k as keyof Customer].length<=300)&&['firstName','lastName','company'].every(k=>c[k as keyof Customer].trim().length>0)&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(c.email)&&/^[+\d\s().-]{6,30}$/.test(c.phone)&&c.phone.replace(/\D/g,'').length>=6}
export function createProject(setup:Setup):Project{if(!validSetup(setup))throw new Error('invalid');return{...setup,...(setup.facility==='port'?{port:{...(setup.port||DEFAULT_PORT)}}:{}),site:{...(setup.site||DEFAULT_SITE)},name:setup.name.trim(),version:2,id:crypto.randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),items:[]}}
export function parseProject(value:unknown):Project{
 const p=value as Project;if(!p||p.version!==2||typeof p.id!=='string'||(!p.id.length||p.id.length>100)||!validSetup(p)||!Array.isArray(p.items)||p.items.length>150||!p.items.every(validItem)||new Set(p.items.map(i=>i.id)).size!==p.items.length||typeof p.createdAt!=='string'||typeof p.updatedAt!=='string'||p.customer&&!validCustomer(p.customer))throw new Error('invalid');
 if(p.location&&(!['countryCode','regionId','city','address'].every(k=>typeof p.location![k as keyof Location]==='string'&&p.location![k as keyof Location].length<=300)||p.location.countryCode!==''&&!/^[A-Z]{2}$/.test(p.location.countryCode)))throw new Error('invalid');
 if(p.loadProfile&&(!['regionId','name','source','snowZone','seismicZone','capturedAt'].every(k=>typeof p.loadProfile![k as keyof LoadSnapshot]==='string'&&String(p.loadProfile![k as keyof LoadSnapshot]).length<=1000)||!Number.isInteger(p.loadProfile.revision)||typeof p.loadProfile.approved!=='boolean'))throw new Error('invalid');
 if(p.items.some(i=>i.access&&!i.access.walkwayIds.every(id=>p.items.some(w=>w.id===id&&w.kind==='walkway'))))throw new Error('invalid');
 if(p.items.some(i=>i.anchor&&!i.anchor.siloIds.every(id=>p.items.some(other=>other.id===id&&isSilo(other)))))throw new Error('invalid');
 if(p.construction){const c=p.construction;if(c.equipmentJobs!==undefined&&(!Array.isArray(c.equipmentJobs)||c.timeline!==2||c.equipmentJobs.length>150||new Set(c.equipmentJobs.map(j=>j.id)).size!==c.equipmentJobs.length||!c.equipmentJobs.every(j=>j&&EQUIPMENT_KINDS.includes(j.kind)&&['install','access'].includes(j.mode)&&p.items.some(i=>i.id===j.id&&i.kind===j.kind&&(j.mode!=='access'||i.kind==='elevator'&&!!i.access))&&!c.siloIds?.includes(j.id)&&!c.walkwayIds?.includes(j.id))))throw new Error('invalid');if(c.timeline!==undefined&&c.timeline!==2||c.aerationIds!==undefined&&(!Array.isArray(c.aerationIds)||new Set(c.aerationIds).size!==c.aerationIds.length||!c.aerationIds.every(id=>c.siloIds?.includes(id)&&p.items.some(i=>i.id===id&&['flat','industrial'].includes(i.kind))))||!Number.isFinite(c.elapsed)||c.elapsed<0||c.elapsed>100000||typeof c.paused!=='boolean'||![1,2,4,6,8].includes(c.speed)||!Array.isArray(c.siloIds)||!Array.isArray(c.walkwayIds)||c.siloIds.length>150||c.walkwayIds.length>150||new Set([...c.siloIds,...c.walkwayIds]).size!==c.siloIds.length+c.walkwayIds.length||!c.siloIds.every(id=>p.items.some(i=>i.id===id&&isSilo(i)))||!c.walkwayIds.every(id=>p.items.some(i=>i.id===id&&i.kind==='walkway')))throw new Error('invalid')}
 return{...(p.location?{location:{countryCode:p.location.countryCode,regionId:p.location.regionId,city:p.location.city,address:p.location.address}}:{}),...(p.loadProfile?{loadProfile:{regionId:p.loadProfile.regionId,revision:p.loadProfile.revision,name:p.loadProfile.name,source:p.loadProfile.source,snowZone:p.loadProfile.snowZone,seismicZone:p.loadProfile.seismicZone,approved:p.loadProfile.approved,capturedAt:p.loadProfile.capturedAt}}:{}),version:2,id:p.id,name:p.name,grain:p.grain,density:p.density,target:p.target,facility:p.facility,width:p.width,depth:p.depth,preferredSilo:p.preferredSilo,language:p.language,currency:p.currency,createdAt:p.createdAt,updatedAt:p.updatedAt,...(p.port?{port:{edge:p.port.edge,quayDepth:p.port.quayDepth,shipGap:p.port.shipGap,shipBeam:p.port.shipBeam,shipLength:p.port.shipLength,hatches:p.port.hatches}}:{}),...(p.design?{design:{location:p.design.location,standard:p.design.standard,snowLoad:p.design.snowLoad,windSpeed:p.design.windSpeed,soilBearing:p.design.soilBearing,seismicPga:p.design.seismicPga,corrosion:p.design.corrosion,throughput:p.design.throughput}}:{}),...(p.site?{site:{setback:p.site.setback,siloGap:p.site.siloGap,foundationApron:p.site.foundationApron,walkwayOverhang:p.site.walkwayOverhang}}:{}),...(p.construction?{construction:{...(p.construction.equipmentJobs?{equipmentJobs:p.construction.equipmentJobs.map(j=>({id:j.id,kind:j.kind,mode:j.mode}))}:{}),...(p.construction.timeline?{timeline:p.construction.timeline}:{}),...(p.construction.aerationIds?{aerationIds:[...p.construction.aerationIds]}:{}),elapsed:p.construction.elapsed,paused:p.construction.paused,speed:p.construction.speed,siloIds:[...p.construction.siloIds],walkwayIds:[...p.construction.walkwayIds]}}:{}),items:p.items.map(i=>({id:i.id,kind:i.kind,x:i.x,z:i.z,y:i.y,rotation:i.rotation,width:i.width,depth:i.depth,height:i.height,...(i.model?{model:i.model}:{}),...(i.rise!==undefined?{rise:i.rise}:{}),...(i.access?{access:{walkwayIds:[...i.access.walkwayIds]}}:{}),...(i.layout?{layout:{group:i.layout.group,row:i.layout.row,column:i.layout.column}}:{}),...(i.anchor?{anchor:{axis:i.anchor.axis,siloIds:[...i.anchor.siloIds]}}:{})})),...(p.customer?{customer:Object.fromEntries(Object.keys(emptyCustomer).map(k=>[k,p.customer![k as keyof Customer]])) as Customer}:{})};
}
export function importProject(raw:string):Project{if(raw.length>2_000_000)throw new Error('invalid');const data=JSON.parse(raw);if(data.version===2)return parseProject(data.project||data);const legacy=decodeProject(raw);const layout=plan(legacy);const p=createProject({name:legacy.name||'Project',grain:legacy.grain,density:legacy.density,target:legacy.capacity,facility:'inland',width:legacy.width,depth:legacy.depth,preferredSilo:legacy.siloType==='flat'?'flat':'economic',language:'tr',currency:'TRY'});p.items=layout.bins.map(b=>({...createItem(b.type==='flat'?'flat':'economic',b.x,b.z),width:b.diameter,depth:b.diameter,height:b.height}));p.items.push(...layout.equipment.map(e=>({...createItem(({office:'building',wetbin:'economic'} as Record<string,Kind>)[e.type]||e.type as Kind,e.x,e.z),width:e.width,depth:e.depth,height:e.type==='wetbin'?5:e.height})));return p}
export function loadProjects(storage:Pick<Storage,'getItem'>):Project[]{const raw=storage.getItem(PROJECTS_KEY);if(raw){const data=JSON.parse(raw);if(!Array.isArray(data)||data.length>100)throw new Error('invalid');return data.map(parseProject)}const legacy=storage.getItem('silo-studio:project:v1');if(legacy){const p=importProject(legacy);p.id='legacy-v1';return[p]}return[]}
export function storeProject(storage:Pick<Storage,'getItem'|'setItem'>,p:Project){p=parseProject(p);const projects=loadProjects(storage),next=[p,...projects.filter(x=>x.id!==p.id)];if(next.length>100)throw new Error('limit');storage.setItem(PROJECTS_KEY,JSON.stringify(next));return next}
export function projectExport(p:Project){if(!validCustomer(p.customer!))throw new Error('invalid');return JSON.stringify({version:2,project:parseProject(p),units:'metres; metric tonnes; kg/m³',summary:{capacityTonnes:p.items.reduce((s,i)=>s+itemCapacity(i,p.density),0),componentCount:p.items.length,currency:p.currency,pricingStatus:'not_configured'},geometryStatus:'Conceptual parametric geometry; manufacturer imagery is reference only.',exportedAt:new Date().toISOString()},null,2)}
export const defaultDensity=(grain:string)=>GRAINS.find(g=>g.id===grain)?.density||600;
