// Reviewed primary sources. Product envelopes in the editor remain adjustable
// concept geometry; these references do not certify a selected SKU or capacity.
export const portSources = [
 {id:28,publisher:'Mysilo',title:'Bant konveyör K model',date:'Revizyon tarihi belirtilmemiş',url:'https://www.mysilo.com/tr/category/98/K-model'},
 {id:29,publisher:'Mysilo',title:'Bant konveyör V model',date:'Revizyon tarihi belirtilmemiş',url:'https://www.mysilo.com/tr/category/99/V-model'},
 {id:30,publisher:'Mysilo',title:'Bant konveyör R model',date:'Revizyon tarihi belirtilmemiş',url:'https://www.mysilo.com/tr/category/100/R-model'},
 {id:31,publisher:'Mysilo',title:'Bant konveyör U model',date:'Revizyon tarihi belirtilmemiş',url:'https://www.mysilo.com/tr/category/211/U-Model'},
 {id:32,publisher:'Mysilo',title:'Zincirli konveyör F serisi',date:'Revizyon tarihi belirtilmemiş',url:'https://www.mysilo.com/tr/category/386/F-Serisi'},
 {id:33,publisher:'Mysilo',title:'Zincirli konveyör S serisi',date:'Revizyon tarihi belirtilmemiş',url:'https://www.mysilo.com/tr/category/387/S-Serisi'},
 {id:34,publisher:'Mysilo',title:'Zincirli konveyör C serisi',date:'Revizyon tarihi belirtilmemiş',url:'https://www.mysilo.com/tr/category/388/C-Serisi'},
 {id:35,publisher:'Mysilo',title:'Tüp konveyör D model',date:'Revizyon tarihi belirtilmemiş',url:'https://www.mysilo.com/tr/category/366/D-Model'},
 {id:36,publisher:'Mysilo',title:'Tüp konveyör L model',date:'Revizyon tarihi belirtilmemiş',url:'https://www.mysilo.com/tr/category/368/L-Model'},
 {id:37,publisher:'Mysilo',title:'U helezonu',date:'Revizyon tarihi belirtilmemiş',url:'https://www.mysilo.com/tr/category/103/U-Helezonu'},
 {id:38,publisher:'Mysilo',title:'Tüp helezon',date:'Revizyon tarihi belirtilmemiş',url:'https://www.mysilo.com/tr/category/105/tup-helezon'},
 {id:39,publisher:'Mysilo',title:'Mobil bant konveyör',date:'Revizyon tarihi belirtilmemiş',url:'https://www.mysilo.com/tr/category/376/Mobil-Bant-Konveyor'},
 {id:40,publisher:'Mysilo',title:'Mobil teleskopik bant konveyör',date:'Revizyon tarihi belirtilmemiş',url:'https://www.mysilo.com/tr/category/377/Mobil-Teleskopik-Bant-Konveyor'},
 {id:41,publisher:'Mysilo',title:'MYPORT gemi yükleme',date:'Revizyon tarihi belirtilmemiş',url:'https://www.mysilo.com/tr/category/434/Gemi-Yukleme-'},
 {id:42,publisher:'Mysilo',title:'Arabalı bant konveyör R model',date:'Revizyon tarihi belirtilmemiş',url:'https://www.mysilo.com/tr/category/454/R-Model'},
 {id:43,publisher:'Mysilo',title:'Arabalı bant konveyör U model',date:'Revizyon tarihi belirtilmemiş',url:'https://www.mysilo.com/tr/category/453/U-Model'},
 {id:44,publisher:'Mysilo',title:'Flat Bottom Silo – F series brochure',date:'Belgede revizyon tarihi doğrulanamadı',url:'https://www.mysilo.com/upload/ckfinder/files/catalogue/en/mysilo-flat-bottom-silo.pdf'},
 {id:45,publisher:'Mysilo',title:'Düz tabanlı silo',date:'Revizyon tarihi belirtilmemiş',url:'https://www.mysilo.com/tr/category/17/duz-tabanli-silo'},
 {id:46,publisher:'Mysilo',title:'Ticari konik silo',date:'Revizyon tarihi belirtilmemiş',url:'https://www.mysilo.com/tr/category/18/ticari-konik-silo'},
 {id:47,publisher:'European Commission, Joint Research Centre',title:'Eurocode 1: Actions on structures',date:'Güncel resmi kapsam sayfası',url:'https://eurocodes.jrc.ec.europa.eu/EN-Eurocodes/eurocode-1-actions-structures'},
 {id:48,publisher:'European Commission, Joint Research Centre',title:'Eurocode 3: Design of steel structures',date:'Güncel resmi kapsam sayfası',url:'https://eurocodes.jrc.ec.europa.eu/EN-Eurocodes/eurocode-3-design-steel-structures'},
 {id:49,publisher:'European Commission, Joint Research Centre',title:'Nationally Determined Parameters',date:'Güncel resmi açıklama',url:'https://eurocodes.jrc.ec.europa.eu/en-eurocodes-implementation/nationally-determined-parameters'},
 {id:50,publisher:'AFAD',title:'Türkiye Deprem Tehlike Haritaları İnteraktif Web Uygulaması',date:'Harita uyarıları; erişim 14 Eylül 2026',url:'https://tdth.afad.gov.tr/TDTH/loginControl.xhtml'},
 {id:51,publisher:'AFAD',title:"Turkey’s New Earthquake Hazard Map is Published",date:'30 Mart 2018',url:'https://en.afad.gov.tr/turkeys-new-earthquake-hazard-map-is-published'},
 {id:52,publisher:'NEUERO',title:'Ship loaders',date:'Revizyon tarihi belirtilmemiş',url:'https://neuero.de/en/produkte/schiffsbelader'},
 {id:53,publisher:'NEUERO',title:'Ship unloaders',date:'Revizyon tarihi belirtilmemiş',url:'https://neuero.de/en/produkte/schiffsentlader'},
 {id:54,publisher:'Galvanizers Association',title:'Atmospheric corrosion',date:'Revizyon tarihi belirtilmemiş',url:'https://galvanizing.org.uk/atmospheric-corrosion/'},
 {id:55,publisher:'Galvanizers Association',title:'Corrosion performance in other environments',date:'Revizyon tarihi belirtilmemiş',url:'https://galvanizing.org.uk/corrosion-performance-in-other-environments/'},
 {id:56,publisher:'Mysilo',title:'Tahıl Depolama Bilgi Kitapçığı',date:'Eski standart referansları içerir; baskı tarihi doğrulanamadı',url:'https://mysilo.com/assets/tahil-depolama-kitapcik.pdf'},
];

export const portSections = [
 {id:'guncel-uygulama',title:'Güncel uygulama: yerleşim, liman ve taşıma',paragraphs:[
 '14 Eylül 2026 tarihli bu genişletme, elle yerleşim yapılan yerel editör içindir. Proje adı, ürün, arsa, silo sayısı, isteğe bağlı ekipmanlar, müşteri bilgisi, yedi dil ve dört para birimi önceki geliştirmelerde uygulanmıştır. Aşağıdaki ilk araştırma bölümlerinde geçen otomatik planlayıcı ve geliştirme önerileri başlangıç çalışmasının kaydıdır; güncel ana arayüzün tamamlanmamış özellik listesi olarak okunmamalıdır.',
 'Bu çalışmada cevaplanan sorular: Konveyör nerede kurulmalı? Hangi Mysilo taşıma aileleri ayrı seçilmeli? Gemiye yükleme için kullanılabilir kara sınırı nerede bitmeli? Kar, rüzgâr ve kıyı ortamı hangi tasarım girdilerini gerektirir? Ürün biçimleri ve kullanım amaçları için öncelik Mysilo sayfalarına; iklim ve yapısal tasarım kapsamı için resmi kurumlara; liman iş akışını çapraz kontrol etmek için gemi yükleme üreticisine verildi. Kaynak sayfalarının revizyonu bilinmediğinde erişim tarihi, yayın tarihi yerine kullanılmadı.',
 'Sonuç olarak 16 taşıma/yükleme seçeneği, yerel üretici görselleri, ürün ailesine göre farklı 3B geometriler, dört yöne dönebilen rıhtım, ayarlanabilir gemi ve kayıtlı tasarım girdileri eklendi. Kar yükünden yalnızca kullanıcı tarafından verilmiş düzgün yayılı çatı yükünün toplam kuvveti hesaplanır. Üretici SKU seçimi, yapısal yeterlilik, kesintisiz tahıl akışı ve uygulama projesi bu modelin çıktısı değildir.'
 ]},
 {id:'liman-tasima',title:'Liman akışı, rıhtım sınırları ve gemiye yükleme',paragraphs:[
 'Kullanıcının tarif ettiği akış, depodaki tahılın gemiye yüklenmesidir. Ship loader bu işi yapar; ship unloader ise gemi ambarından ürünü karaya alır. İki makine aynı isim altında seçilmemelidir. Mysilo MYPORT ve mobil teleskopik bant seçenekleri gemiye yükleme tarafında değerlendirilmiştir. NEUERO’nun ayrı yükleme/tahliye ürünleri de bu işlev ayrımını doğrular; onun makineleri Mysilo modeli olarak kopyalanmamıştır. [40] [41] [52] [53]',
 'Önerilen işletme zinciri ana stok → silo boşaltma hattı → transfer/elevatör → rıhtım taşıma hattı → yükleyici → gemi ambarıdır. Bu bir ön proje akış önerisidir. Numune, tartım, toz toplama, yönlendirme klapeleri ve bakım erişimi gerçek işletme ihtiyacına göre eklenir. Hat debisi tek bir büyük makinenin kapasitesiyle belirlenemez; besleyen ve boşaltan ekipmanların birlikte çalışması gerekir. Uygulamadaki hedef t/h alanı müşteri talebini kaydeder, otomatik makine kapasitesi veya motor gücü seçmez.',
 'Editörde arsa ana kara parselidir; rıhtım seçilen kıyı kenarının dışına eklenir. Kıyı kuzey, güney, doğu veya batı olabilir. Silolar kendi temel ve çevre paylarıyla parsel içinde kalır. Konveyörler rıhtıma uzanabilir. Yeni gemi yükleyicilerin taşıyıcı tabanı rıhtım üzerinde kalır; uzatma kolu suya erişebilir. Böylece uzun bomun bütünü kara tabanı gibi yorumlanmaz. Görünüm, yerleşim denetimi, 2B plan ve gemi ambarı kontrolü aynı kıyı koordinatlarını kullanır.',
 'Başlangıç rıhtımı 14 m, gemi-kıyı boşluğu 3 m, gemi eni 20 m, boyu 90 m ve ambar sayısı 4 olarak seçildi. Bunlar değiştirilebilir görsel başlangıç değerleridir; mevcut limana ait ölçüm veya zorunlu standart mesafesi değildir. Kullanıcı gerçek iskele projesi ve hedef gemiyle değiştirmelidir. Birbirine sığmayan gemi eni/boyu veya ambar sayısı kayda alınmaz. Yükleyici ucunun ambarın plan izdüşümüne ulaşıp ulaşmadığı gösterilir; gemi draftı, gelgit, trim, hareket, borda geçiş yüksekliği ve bom çalışma zarfı henüz çözülmez.',
 'Deniz artık parsel kadar küçük bir dikdörtgen değildir. Kıyıdan dışarı uzanan geniş bir yüzey, hareketli ışık/dalga ayrıntısı, rıhtım tamponları, babalar, bağlama hatları ve açık ambarlı dökme yük gemisi kullanılır. Bu çevre görsel bağlam sağlar; hidrografik harita, su derinliği, yaklaşma kanalı, rıhtım taşıma gücü ve işletme izni yerine geçmez.'
 ]},
 {id:'mysilo-konveyorler',title:'Mysilo taşıma kataloğu ve model karşılıkları',paragraphs:[
 'Bantlı grup dört ayrı seçim içerir: K, V, R ve U. K için kapalı modüler kasa; V için açık bant ve rulolar; R/U için farklı oranlarda taşıyıcı gövde ve üretici görsellerindeki bombeli kapak biçimi kullanıldı. Sayfalarda açık/kapalı düzen, boy ve kapasite anlatımları modele göre değişir; tek bir “konveyör” kutusuyla bütün aileleri temsil etmek uygun değildir. Editördeki uzunluk, genişlik ve kotlar düzenlenebilir yerleşim ölçüleridir. [28] [29] [30] [31]',
 'Zincirli grup F · H, S · HI ve C olarak ayrıldı. F ve S üretici serileridir; H ve HI burada görsel olarak temsil edilen düzenlerdir. F içindeki bütün H/BH/IH/U veya S içindeki bütün HI/I/HIH alt tipleri ayrı SKU olarak uygulanmış değildir. F için düz kapalı modüller; S için yatay başlangıç ve yükselen bölüm; C için daha kompakt boşaltma kasası, kapaklar, flanşlar ve tahrik kullanıldı. [32] [33] [34]',
 'D ve L tüp konveyörlerde üretici resimlerindeki paralel tüp/geri dönüş düzeni farklı geometrilerle gösterilir. U helezonunda açık oluk, şaft ve helis; tüp helezonda kapalı boru ve tahrik bulunur. Tüp konveyörün kapalı taşıma devresi ile helezonun dönen vidalı mekanizması aynı makine olarak sunulmaz. Eğim/yükselti girilebilmesi, her ürünün bu eğimde istenen kapasiteyi sağlayabileceği anlamına gelmez. [35] [36] [37] [38]',
 'Mobil bant; tekerlek, eğimli kafes taşıyıcı ve kaldırma bağlantılarıyla temsil edilir. Mobil teleskopik bant ayrı gemi yükleme seçeneğidir. MYPORT modelinde üretici görselinden portal kule, platformlar, silindirik/konik gövdeler, taşıyıcı bom ve aşağı uzanan yükleme ucu ayrıştırıldı. R ve U arabalı bantlarda ise yüksek boşaltma bölümü ve yönlendirme ağzı bulunur. Hareketli arabanın hat boyunca seyri ve ürünün dinamik akışı bu sürümde simüle edilmez. [39] [40] [41] [42] [43]',
 'Toplam 16 modelin seçim kartındaki SVG/PNG/JPG dosyası üreticinin kendi ürün sayfasından alınmıştır. Dosyalar yereldir; editör açıldığında üretici sunucusuna bağlı kalmaz. Her dosyanın kaynak sayfası, medya adresi ve inceleme tarihi varlık manifestinde tutulur. 3B nesneler bu görsellerle aynı CAD dosyası değildir: sahne için geliştirilen parametrik geometrilerdir. Birebir imalat geometrisi için revizyonu belli üretici CAD/GLB dosyaları ve model kodları gerekir.',
 'Kapasite verisinde dikkat çeken açık nokta birim tutarlılığıdır: U sayfasındaki tanıtım anlatımıyla teknik tabloda kullanılan m³/h birimi aynı biçimde yazılmamıştır. Bu nedenle başlık rakamları doğrudan t/h olarak içe aktarılmadı. Kütlesel debi, doğrulanmış hacimsel debi ile gerçek yığın yoğunluğundan türetilir: t/h = m³/h × kg/m³ ÷ 1000. Bant hızı, doluluk, eğim, ürün ve kesin model kodu doğrulanmadan uygulama nominal performans puanı göstermez. [31]'
 ]},
 {id:'liman-silo-secimi',title:'Liman ve kara tesisi için depolama seçimi',paragraphs:[
 'Liman seçimi bütün siloları farklı bir gövdeye dönüştürmez. Mysilo düz tabanlı siloları yüksek tonajlı ve uzun süreli stok için tanımlar; ticari konik silolar farklı boşaltma/işletme ihtiyaçlarına cevap verir. Buradan çıkan ön proje önerisi, büyük liman ana stoklarında düz tabanlı veya endüstriyel ana depoları, hızlı parti geçişi ve kısa süreli tampon ihtiyacında uygun konik çözümleri birlikte değerlendirmektir. Bu bir zorunlu ürün reçetesi değildir. [45] [46]',
 'Silo adedi toplam tonaja ek olarak ürün ve kalite ayrımı, aynı anda gemiye ayrılan parti, kabul ve yükleme sırasında hatların paylaşımı, bakımda yedeklilik ve büyüme ihtiyacına bağlıdır. Kare, yem ve geçici depolama seçenekleri otomatik olarak yasaklanmadı; uygunluk müşterinin ürününe ve işletme amacına göre değerlendirilir. Arayüzde liman için ana stok/tampon ayrımı kısa bir notla açıklanır; karar kullanıcıda kalır.',
 'Gerçek çap, halka sayısı, gövde sacı, stiffener, çatı taşıyıcıları ve ankraj seçimi yalnız depolama hacminden çıkmaz. Mysilo ürün ve F serisi belgeleri saha rüzgârı, karı ve deprem koşullarının tasarımla ilişkisini belirtir. Editörde iklim girdisi değişince görsel sac kalınlığına rastgele bir katsayı uygulanmaz; modelin uygun olduğunu söylemek için üretici hesap revizyonu gerekir. [44] [45]'
 ]},
 {id:'saha-yukleri',title:'Kar, rüzgâr, deprem, zemin ve kıyı ortamı',paragraphs:[
 'Kar için zemindeki karakteristik kar yükü ile çatıda uygulanacak yük ayrılmalıdır. Çatı biçimi, kar dağılımı ve birikme durumları tasarım standardına bağlıdır. Rüzgârda temel hız tek başına basınç ve taşıyıcı kuvvet sonucu değildir. JRC kapsam sayfası kar için EN 1991-1-3, rüzgâr için EN 1991-1-4, silo/tank etkileri için EN 1991-4; çelik silo tasarımı için EN 1993-4-1 gibi ayrı başlıklar gösterir. Projede uygulanacak baskı ve ulusal ek yetkili tasarımcı tarafından belirlenmelidir. [47] [48]',
 'Ülke ve saha önemlidir: Eurocode ulusal parametreleri, ilgili ülkenin iklim/coğrafya koşullarını ve ulusal tercihlerini kapsar. Uygulama konum ve standart/ulusal ek metniyle birlikte çatı kar yükünü kN/m², temel rüzgâr hızını m/s, deprem PGA değerini g, zemin taşıma girdisini kPa olarak saklar. Boş alanlar null kalır. Eksik bilgi sıfır yük veya risksiz saha olarak kabul edilmez; girilmiş alan sayısı tasarım onayı değil veri tamlığı göstergesidir. [49]',
 'Kar özeti yalnız düzgün yayılı kullanıcı çatı yükü × yatay çatı izdüşüm alanıdır. Dairesel siloda alan πD²/4, kare siloda en × boy alınır. Örneğin 10 m çapta 1,2 kN/m² yük yaklaşık 94,2 kN toplam kuvvet verir. Bu basit aritmetik, birleşik yük halleri, dengesiz kar birikmesi, burkulma, bağlantı, temeller veya malzeme dayanımı hesabı değildir. Zemindeki kar haritası değeri doğrudan bu alana taşınmamalıdır.',
 'Türkiye için eski “deprem bölgesi” numarasını yeni bir proje varsayımı yapmak uygun değildir. AFAD yeni haritayı 2018’de duyurmuş, 2019 yürürlüğünü açıklamış ve bölge yerine koordinata bağlı tehlike değerlerine geçmiştir. Harita uygulaması da yerel zemin büyütmesi, sıvılaşma ve oturma etkilerinin ayrıca değerlendirilmesi gerektiğini bildirir. Tek PGA girdisi bir silo için deprem tasarımını tamamlamaz; spektrum, zemin sınıfı, önem ve davranış parametreleri ayrıca gerekir. Bu sürüm AFAD oturumuna girmez veya otomatik değer çekmez. [50] [51]',
 'Kıyıda korozyon, yağışla yıkanma, klorür, ıslanma-kuruma ve su sıçrama koşulları kaplama ömrünü etkileyebilir. Deniz atmosferi ile sürekli su altında veya gelgit/sıçrama bölgesindeki davranış aynı değildir. Bu nedenle kara ve liman projelerinde korozyon sınıfı ayrıca kaydedilir; liman seçildi diye otomatik C5/CX atanmaz. Kullanıcı sınıfı ve kaplama sistemi saha değerlendirmesiyle belirlemelidir. Renkli 3B malzeme galvaniz kalınlığı veya korozyon dayanımı belgesi sayılmaz. [54] [55]',
 'Kaynaklar arasında dönem farkı bulunur. Mysilo’nun eski depolama kitapçığında eski deprem/standart referansları ve belirli ürün koşullarına ait rüzgâr/kar kabulleri vardır; bunlar bütün sahalara güncel varsayılan olarak kopyalanmadı. F serisi broşürü saha yüklerinin belirlenmesini vurgular. Eski katalogdaki sayı, yeni lokasyon ve güncel sipariş şartının yerine geçmez. Kullanılacak standart baskısı ve ürün tasarım esasları üreticiyle teyit edilmelidir. [44] [56]'
 ]},
 {id:'konum-kurulum-dogrulama',title:'Konum, montaj animasyonu ve doğrulama sınırları',paragraphs:[
 'Yerleştirme hatasının nedeni son nesnenin koordinatını kaybetmesi değildi: montaj alanı parselin sabit tarafına öncelik veriyor, yeni iş başlayınca kamera yeniden ortalanıyordu. Montaj adayları artık tıklanan noktaya uzaklığıyla sıralanır. Boş ve yeterli alanda konveyör doğrudan tıklanan konumda zeminde birleştirilir; sonra o konumun üstündeki seçilmiş kota kaldırılır. Yerleştirmenin 0,5 m konum adımı korunur. Kamera her yeni ekipmanda başlangıç açısına dönmez.',
 'Silo veya başka ekipmanla dolu bir noktadaki üst kot hattı için zeminde aynı yerde montaj mümkün olmayabilir. Böyle bir durumda yakın uygun montaj alanı aranır; yeterli alan yoksa işlem başlamaz. Kaydedilen nihai x/z koordinatı bu arama nedeniyle değiştirilmez. Vinç, işçi ve montaj rezervi gerçek kaldırma planı değildir; saha uygulanabilirliği ayrıca doğrulanmalıdır. Rıhtım da montaj için kullanılabilir kara hesabına katılır, su montaj alanı sayılmaz.',
 'Otomatik doğrulamalar farklı konumlarda konveyörün başlangıç ve bitiş koordinatlarını, bütün üretici varyantlarının sonlu geometrisini, yerel görselleri ve kayıt kimliğini, dört kıyı yönünün sınırlarını, ambar erişimini, kurulum sonu geometri eşitliğini, deniz alanını ve boş/yanlış yük girdilerini kapsar. Bunlar yazılım ve geometri kontrolleridir; üretici performans testi veya statik mühendislik onayı değildir.',
 'Sonraki teknik veri entegrasyonunun sırası: kesin SKU ve revizyonlu CAD → doğrulanmış kapasite tabloları → bağlantı ağı ve debi/kot uyumu → işletme/bakım zarfları → saha yüklerine göre üretici tasarım seçimi → mühendis incelemesi ve teklif. Yeni model dosyaları geldiğinde gerçek görsel ile parametrik model arasındaki fark kapatılabilir. Böylece yerleşim özgürlüğü korunurken teklif ve uygulama çıktısı gerçek ürün verisine dayanır.'
 ]},
];
