import {portSections} from './port-research';
export const researchSections = [
 ...portSections,
 {id:'kapsam',title:'Tesisin kapsamı ve terminoloji',paragraphs:[
 'Bir tahıl tesisi, ürün kabulünden sevkiyata kadar birbirine bağlı bir sistemdir. Ana stok hacmi; taşıma hatları, şartlandırma, numune alma, kalite ayrımı, araç hareketleri ve işletme disipliniyle birlikte ele alınmalıdır. Kuzey Amerika kataloglarında grain bin, grain storage bin, grain leg; Avrupa ve Türkiye kataloglarında steel silo, grain storage silo, bucket elevator, flat-bottom ve hopper-bottom ifadeleri kullanılır. Ürün ararken yalnızca silo kelimesi kullanılması silaj, çimento ve sıvı depolarını da sonuçlara getirir. Tahıl ürünü, malzeme ve boşaltma biçimi birlikte belirtilmelidir. [1] [11] [26]',
 'Ön proje için doğru başlangıç, müşteri bilgi formu ve tasarım esasları belgesidir. Bu çalışmanın yazılım önerisi; her kararın girdisini, hesap yöntemini, kaynağını ve doğrulanma durumunu aynı proje içinde tutmaktır. “Üretici verisi”, “kullanıcı ölçümü”, “geometrik tahmin” ve “temsili ekipman” birbirinden ayrılmalıdır. Böylece bir katalogdan alınan çapın, aynı katalogdaki taşıma kapasitesi veya statik yeterlilikle karıştırılması önlenir.',
 'İlk uygulama Türkiye odaklı ticari tesislerin ön yerleşimini hedefler. Örnek senaryo 6.000 ton buğday ve 120 × 85 metre dikdörtgen arsadır. Girdiler değiştirilebilir. Bu ölçek seçimi bir pazar büyüklüğü tahmini değildir; geliştirme kapsamıdır. Arsa poligonu, farklı ürünlerin birlikte stoklanması, gerçek marka/model eşleştirmesi ve teklif maliyeti sonraki geliştirme aşamalarında ele alınacaktır.'
 ]},
 {id:'musteri',title:'Müşteriden alınacak bilgiler',paragraphs:[
 'Ürün dosyasında ürün türü, çeşidi, kullanım amacı, hasat bölgesi, ölçülmüş yığın yoğunluğu, giriş nemi dağılımı, sıcaklığı, yabancı madde oranı, kırık tane oranı ve hedef kalite sınıfı bulunmalıdır. Tohumluk ve maltlık ürünlerin kalite hedefleri yemlik ürünle aynı değildir. Müşterinin beyan ettiği toplam tonaj, aynı anda tutulacak stok mu yoksa yıllık işlem hacmi mi olduğu belirtilmeden tasarıma alınmamalıdır.',
 'İşletme dosyası; pik günlük kabul, çalışma saatleri, araç başına yük, aynı anda boşaltılacak araç sayısı, sevkiyat hızı, farklı partilerin sayısı ve sezon dışı kullanımını kapsamalıdır. Altı farklı kalite partisi tutulacaksa tek bir büyük silo toplam tonajı karşılasa bile işletme ihtiyacını karşılamaz. İlk sürümde “en az parti” girdisi, bu gereksinimin basitleştirilmiş karşılığı olarak asgari silo sayısına uygulanır. Parti başına farklı kapasite henüz atanmaz.',
 'Saha dosyasında ölçülü sınır, kuzey, kotlar, topoğrafya, yol bağlantısı, mevcut yapılar, irtifaklar, çekme mesafeleri, yükseklik sınırı, zemin etüdü, yeraltı suyu, elektrik gücü ve yakıt kaynağı yer almalıdır. Bir arsaya makine yerleştirmek için sadece metrekare bilgisi yeterli değildir. Aynı alandaki dar uzun ve kare parsellerin araç dolaşımı, konveyör uzunluğu ve büyüme olanağı farklıdır.',
 'Teslim beklentileri ayrıca kaydedilmelidir: yalnız ekipman tedariki, temel dahil anahtar teslim, otomasyon, operatör eğitimi, yedek parça, performans testi ve bakım kapsamı. Belirsiz kalan bilgiler tahminle sessizce doldurulmamalı; ön proje varsayımı olarak işaretlenmelidir. Yazılımın önerilen müşteri akışı ürün → işletme → saha → teknoloji → alternatifler → teknik inceleme sırasını izler.'
 ]},
 {id:'urun',title:'Ürün özellikleri ve depolanabilirlik',paragraphs:[
 'Depolama kütlesi hacim ile yığın yoğunluğunun çarpımıdır. Bu yoğunluk, tane malzemesinin gerçek yoğunluğu değildir; taneler arası boşlukları da içerir. Çeşit, nem, saflık ve yerleşme durumuna bağlıdır. Cimbria Delta 145 tablosu örneğin buğday için 0,76 t/m³, mısır için 0,71, soya için 0,72, ayçiçeği için 0,40 ve çeltik için 0,51 değerlerini kendi performans koşullarında kullanır. Bu değerler tüm partiler için sabit fiziksel özellik sayılmamalıdır. [7]',
 'Uygulamada başlangıç yoğunlukları buğday 769, mısır 720, arpa 640, soya 720, ayçiçeği 400 ve çeltik 510 kg/m³ olarak kullanılır. İlk üç değer Mysilo kapasite tablosundaki referans yoğunluk sınıflarıyla uyumludur; ürünlere eşleştirilmesi ön proje varsayımıdır. Diğer üç değer Cimbria örneklerinden alınmıştır. Kullanıcı bunları numune ölçümüyle değiştirmelidir. Aynı silo hacminde 400 kg/m³ ürün, 769 kg/m³ ürünün yaklaşık %52’si kadar kütle tutar. [2] [7]',
 'Nem hedefi ürün, sıcaklık, depolama süresi ve son kullanım koşuluyla tanımlanmalıdır. University of Minnesota, buğday ve arpa kurutmada %13–14 aralığını genel çerçeve olarak verir. Aynı kurumun sıcak dönem depolama rehberi daha düşük hedefler belirtir: mısır %13–14, soya %11–12, buğday %13, arpa %12 ve yağlık ayçiçeği %8. Bu fark çelişki değil; depolama koşulu ve süre farkıdır. Minnesota kış sıcaklıkları Türkiye için doğrudan işletme reçetesi değildir. [4] [6]',
 'İlk sürümde nem değerleri düzenlenebilir senaryo girdileridir; güvenli depolama garantisi vermez. Arpa %12 ve ayçiçeği %8 başlangıç hedefiyle açılır. Çeltik için %13 yalnızca yer tutucu proje varsayımıdır; çeşit, çatlama, randıman ve kademeli kurutma reçetesi ayrıca alınmalıdır. Yağlı tohumlar ve çeltik için ürün özel inceleme uyarısı gösterilir. Sıcaklık, nem ve süreye bağlı izin verilebilir depolama ömrü modeli henüz uygulanmamıştır.'
 ]},
 {id:'silo',title:'Silo tipi ve kapasite hesabı',paragraphs:[
 'Düz tabanlı çelik silolar uzun süreli ve yüksek hacimli stok için yaygın bir çözümdür. Mysilo ürün sayfası 4,58–41,25 metre çap aralığı bildirir. OBIAL farklı bir ürün ailesinde 3,67–32,72 metre aralığı verir. Bu fark, tüm üreticilerin tek bir evrensel modüler çap dizisi kullanmadığını gösterir. Üretici model kodu, çap, gövde yüksekliği ve hacim aynı kayıt altında tutulmalıdır. [1] [21]',
 'Konik tabanlı silo; yerçekimiyle boşaltma, sık parti değişimi, tamponlama veya proses beslemesi için değerlendirilebilir. Bununla birlikte bir koninin bulunması tüm ürünlerde tam boşalmayı, kütlesel akışı veya FIFO işletmesini tek başına kanıtlamaz. Duvar sürtünmesi, ürün akış özellikleri, çıkış ölçüsü ve koni açısı üreticiyle belirlenmelidir. Bu yazılımın hopper modeli bir geometrik hacimdir; akış garantisi değildir.',
 'Ön hesapta r = D/2, Vsilindir = πr²H, Vüst = πr² × (r tan 28°)/3 alınır. Konik taban seçilirse 45° varsayımıyla Valt = πr³/3 eklenir. Kullanılabilir hacim, bu toplamın %95’idir. Kütle ton = Vkullanılabilir × yoğunluk kg/m³ ÷ 1000. %95 dolum katsayısı uygulama varsayımıdır; kullanıcıya bildirilen hesap esasıdır. H, silindirik gövde yüksekliğidir; zemin ile çatı tepesi arası mesafe değildir.',
 'Mysilo’nun 800 kg/m³ tablosu kapasite hesabında %6 sıkışma ve 28° yığılma açısı kullandığını belirtir. Bu uygulama sıkışma artışı uygulamaz. Bu nedenle aynı çap ve gövde yüksekliği seçilse bile marka kataloğundaki tonajla birebir eşleşme beklenmez. Üst ürün yığını ile fiziksel çatı arasındaki boşluk da gerçek ürün tasarımından doğrulanmalıdır. Statik duvar yükü hesabı hacim hesabından türetilemez. [3]',
 'Düz taban boşaltmada merkez çıkış, ara çıkışlar, helezon veya zincirli çıkarma hattı ve dip süpürücü birlikte ele alınmalıdır. Dip süpürücü ve üst yürüme yolları üretici ekipman kataloğunda ayrı bileşenlerdir. İlk sürüm bunların yapısal ve mekanik hesabını yapmaz; ana silo ve üst hatları şematik gösterir. [25]'
 ]},
 {id:'akis',title:'Ürün akışı ve taşıma hatları',paragraphs:[
 'Önerilen genel akış; giriş kaydı ve numune → tartım → alım çukuru → kaba temizleme ve aspirasyon → gerekirse yaş ürün tamponu → kurutma ve soğutma → depolama → geri alma → sevkiyat tartımıdır. Kuru ürün için kurutucu bypass hattı, farklı ürünler için ayrı rotalar ve bakım için erişim düşünülmelidir. Bu bir kavramsal proses önerisidir; her tesisin kabul protokolü ve ürün hattı ayrıca tanımlanır.',
 'Kovalı elevatör dikey taşıma, zincirli konveyör ve bant konveyör yatay dağıtım, helezon kısa mesafe aktarım ve boşaltma işlerinde değerlendirilen ekipman aileleridir. Silos Córdoba endüstriyel ürün listesi bunları, sürgülü klapeler ve dip süpürücülerle birlikte sunar. Seçim; mesafe, kot, ürün hassasiyeti, çalışma süresi, temizlenebilirlik ve kapasiteye göre yapılmalıdır. [11]',
 'Günlük kabulün çalışma saatine bölünmesi ortalama gerekli debiyi verir: 800 ton/gün ÷ 10 saat/gün = 80 t/sa. Bu değer pik kamyon boşaltma debisi değildir. Örneğin 25 tonluk bir aracın 10 dakikada boşaltılması anlık 150 t/sa kabul gerektirebilir. Çukur tamponu, vardiya dağılımı ve hat eşzamanlılığı bu farkı karşılamalıdır. Yazılım bugün ortalamayı gösterir; araç kuyruğu veya dinamik tampon simülasyonu yapmaz.',
 'Bir hattın performansını en dar kapasite ve ürün koşulu belirler. Referans olarak Delta 145’in buğday ön temizleme tablosundaki 60 t/sa değeri, 80 t/sa hedefli örnek tesise otomatik uygun sayılmaz. Aynı veri sayfası nem ve yabancı madde değişiminin kapasiteyi etkilediğini söyler. Bu nedenle uygulamadaki temizleyici görünümü gerçek Delta 145 seçimi değildir. [7]',
 'Zincirli taşıma hatlarında taşma, dönme ve sıcaklık algılama gibi izleme noktaları ürün tasarımının bir parçasıdır. Silos Córdoba’nın ağır hizmet zincirli konveyörü bu tip sensörleri açıklamaktadır. İlk sürümde turuncu üst bağlantılar yalnızca şematik rota gösterir; taşıyıcı köprü, destek kulesi, tahrik gücü, eğim, klape ve çakışma çözümü yerine geçmez. [10]'
 ]},
 {id:'kurutma',title:'Kurutma, havalandırma ve kütle dengesi',paragraphs:[
 'Kurutma üründen su uzaklaştırır; depolama havalandırmasının başlıca amacı ise tane sıcaklığını yönetmek ve depolama koşullarını düzenlemektir. University of Minnesota düşük sıcaklıklı doğal hava kurutmasını yüksek sıcaklıklı kurutmadan ayırır; doğal hava kurutmasının haftalar sürebildiğini belirtir. Bu nedenle küçük bir depolama fanının varlığı, yüksek nemli ürün için endüstriyel kurutucu kapasitesinin bulunduğu anlamına gelmez. [4]',
 'Sürekli akışlı kurutucuda ürün, kurutma ve soğutma bölümlerinden geçer. Cimbria karışık akışlı modüler kurutma kolonlarını, değişken boşaltma ve hava dağılımı elemanlarıyla açıklar. Gerçek seçim için giriş ve hedef nemi, ürün, ortam sıcaklığı ve bağıl nemi, yakıt, enerji verimi, kalite kaybı ve garanti koşulları birlikte istenmelidir. [8] [9]',
 'Yaş bazda nemler kullanıldığında kuru madde korunumu: Mkuruürün = Myaşgiriş × (100 − nin)/(100 − nout). Uzaklaştırılan su = Myaşgiriş − Mkuruürün. Örnek senaryoda 80 t/sa ürün %16’dan %13,5’e indirildiğinde yaklaşık 2,31 t/sa su uzaklaşır; çıkış yaklaşık 77,69 t/sa olur. Bu matematiksel denge yabancı madde ayırma, tane kaybı veya yakıt tüketimini içermez. Kurutucu t/sa değeri yerine kullanılmamalıdır.',
 'Yaş tampon kapasitesi, saatlik kabul ve kurutma farkının süre boyunca birikmesinden hesaplanmalıdır. Tek bir sabit tampon silosunun her senaryoya yeterli olduğu varsayılmamalıdır. Bu sürüm yaş tamponunu yerleşim rezervi olarak gösterir ve ana stok tonajına katmaz. Gerçek hacim, bekleme süresi ve sıcak ürün riskleri için ayrı boyutlandırma gereklidir.',
 'Depolama izleme planı sıcaklık kabloları, fan çalışma kayıtları, nem kontrolü ve gerektiğinde numune analizini içermelidir. UMN, nem göçü ve sıcaklık farklarının bozulmaya yol açabildiğini; tahılın düzenli izlenmesi gerektiğini vurgular. Türkiye’deki iklim ve işletme koşulu için fan kontrol stratejisi yerel uzmanlıkla uyarlanmalıdır. Uygulama fan gücü, statik basınç ya da hava dağılımı çözmez. [5]'
 ]},
 {id:'arsa',title:'Arsa yerleşimi ve optimizasyon yaklaşımı',paragraphs:[
 'Yerleşim tasarımında önce parselin kullanılabilir bölgesi belirlenir. Bina yaklaşma sınırları, mevcut yapılar, enerji hatları, kapılar, yangın erişimi, kamyon manevrası, drenaj, bakım ve gelecekteki genişleme alanları ayrı katmanlardır. Ekipman yalnız nominal sac çapıyla değil, temel çıkması, fan, merdiven, servis boşluğu ve bağlantılarıyla birlikte değerlendirilmelidir.',
 'Mevcut algoritma iki yerleşim yönünü dener. Seçilmiş çaplar ve gövde yükseklikleri arasından hacim hesabıyla silo adedi bulur; asgari parti sayısını korur. Dış sınır mesafeleri çıkarılır, kurutuculu tesiste 32 metre, kurutucusuz tesiste 22 metre derinlikte ekipman bölgesi ayrılır. Bunlar yazılımın başlangıç rezervleridir; resmi güvenlik mesafesi değildir.',
 'Aday silolar satır ve sütun düzeninde yerleştirilir. Kapasite hedefini karşılamayan veya dikdörtgen depolama alanına sığmayan adaylar elenir. Kalan adaylar fazla kapasite, silo sayısı, kaplanan alan ve yükseklik ağırlıklarıyla sıralanır. Bu skor satın alma maliyeti değildir ve küresel optimum kanıtı sunmaz. Mevcut katalog aramasında en fazla 36 ana silo vardır.',
 'Ekipman bandında alım çukuru, elevatör, isteğe bağlı temizleyici ve kurutucu, yaş tamponu ve kontrol binası bulunur. Nominal yerleşim zarfı için yeterli alan kontrol edilir. Ancak araç dönüş eğrisi, bağlantı borusu eğimi, elevatör kulesi statik modeli, patlama tahliye yönü ve inşaat vinci çalışma alanı çözülmez. “Yerleşim oluşturuldu” mesajı yalnız bu geometrik aday aramasının başarılı olduğunu anlatır.',
 'İkinci aşama önerisi: GeoJSON veya ölçülü poligon girişi, kapı ve engel çizimi, tekil sürükleme, çakışma geri bildirimi, bakım zarfları, kamyon dönüş şablonları ve büyüme rezervi. Üçüncü aşamada farklı üreticilerden doğrulanmış SKU aileleri ve alternatif maliyetler eklenebilir. Kullanıcı bir kuralı değiştirdiğinde sonuçta hangi kısıtın aktif olduğu açıklanmalıdır.'
 ]},
 {id:'insaat',title:'İnşaat, montaj ve devreye alma',paragraphs:[
 'Önerilen proje sırası: ihtiyaç ve saha verilerinin onayı; kapasite ve proses alternatifleri; üretici ön seçimi; jeoteknik ve yük verileri; mimari, statik, mekanik ve elektrik projelerinin koordinasyonu; izinler; satın alma; saha altyapısı; temel; ekipman montajı; otomasyon; boşta ve ürünlü testler; kabul ve eğitim. Bu sıra genel bir iş kırılımıdır. Saha ve sözleşmeye göre bazı işler paralel yürüyebilir.',
 'Temel hesabına yalnız ürün tonajı değil; gövde, çatı, ekipman, kar, rüzgâr, deprem, asimetrik boşaltma ve ankraj etkileri girer. Brock temel rehberi zeminin, kotun, ankrajın, fan ve rijitleştirici desteğinin önemini vurgular. Bu yüzden uygulamadaki beton daireler sadece görsel temel alanıdır; radye kalınlığı, donatı, zemin emniyeti veya ankraj planı vermez. [13]',
 'Saha drenajı, temele su girişini ve alt bölgedeki ürünün ıslanmasını önlemeye yönelik tasarlanmalıdır. Brock bakım kılavuzu temel çevresindeki drenajın saha planında ele alınmasını, kurulum ve ilk dolum sonrası kot ölçümlerinin kaydedilmesini önerir. Temel oturmasının izlenmesi, devreye alma dosyasına ölçülebilir bir başlangıç kaydı ekler. [14]',
 'Montaj planı üreticinin onaylı kılavuzu, kaldırma düzeni, çalışma koşulları ve ekipman sırasına göre hazırlanır. Gövde ve çatı elemanlarının sahada sıralanması, sızdırmazlık, ankraj ve bağlantı kontrolleri için üretici denetim kayıtları gerekir. Mysilo, mekanik montaj gözetimi, yetkin elektrik montajı, devreye alma ve operatör eğitimi hizmetlerini birlikte tanımlar. Buradaki görseller montaj talimatı değildir. [15]',
 'Önerilen kabul dosyasında malzeme ve teslim listeleri, uygunluk belgeleri, montaj kontrol kayıtları, topraklama ve elektrik ölçümleri, motor yönleri, sensör ve kilitleme testleri, alarm senaryoları, boşta deneme, ürünlü kapasite denemesi ve kalite ölçümleri bulunur. Performans denemesi ürün, nem, çalışma süresi ve ölçüm cihazları belirtilmiş bir protokole dayanmalıdır. Teslimden sonra kullanım talimatı, yedek parça, eğitim, bakım periyodu ve garanti kapsamı işletmeye devredilir.'
 ]},
 {id:'guvenlik',title:'İşletme güvenliği ve tasarım sınırları',paragraphs:[
 'Tahıl tozu yangın ve patlama, ürün içine gömülme, sıkışma, hareketli makine ve yüksekten düşme riskleri doğurabilir. OSHA 1910.272, ABD tahıl elleçleme tesisleri için toz kontrolü, eğitim, bakım, kilitleme ve tahıl içine giriş gibi başlıkları düzenler. Bu kaynak iyi uygulama araştırması için kullanılmıştır; Türkiye’de doğrudan mevzuat uygunluğu belgesi olarak kullanılamaz. [16]',
 'Patlama riski değerlendirmesi ekipman seçiminden sonra eklenen bir etiket değildir. Toz oluşum noktaları, toplama sistemi, tutuşturucu kaynaklar, zon sınıflandırması, tahliye veya bastırma, izolasyon ve emniyetli boşaltım yönleri uzman tasarımına bağlanmalıdır. Alım çukuru aspirasyonu için Cimbria ayrı sistem seçenekleri sunar. Çalışma ve Sosyal Güvenlik Bakanlığı tarım rehberi de silo ve tahıl ambarlarını sınırlanmış alan örnekleri arasında ele alır. [12] [27]',
 'İlk uygulama bir risk analizi aracı değildir. Uyarı listesi, eksik tasarım başlıklarını görünür kılmak için bulunur. Sabit mesafelerden “ATEX uygun”, “yangın güvenli” veya “kuruluma hazır” sonucu üretilmez. Personelin silo içine girmesi, tahıl üzerinde yürümesi veya çalışan ekipmana müdahalesi için operasyon talimatı oluşturulmamıştır.',
 'Otomasyonun ileriki kapsamı; seviye, sıcaklık, yatak sıcaklığı, bant kaçıklığı, hız, tıkanma ve fan geri bildirimlerini ekipman grafiğine bağlamaktır. Çalıştırma ve durdurma sıraları ile acil duruş tasarımı yetkin otomasyon ekibinin onayına tabidir. Bir ekrandaki animasyonun gerçek tesisi kontrol etmesi bu sürümün kapsamı değildir.'
 ]},
 {id:'mevzuat',title:'Türkiye mevzuatı ve standart doğrulaması',paragraphs:[
 'Lisanslı depoculuk ile özel işletmenin kendi ürün deposu aynı hukuki statü değildir. Ticaret Bakanlığının güncel mevzuat dizini 5300 sayılı Kanunu, Tarım Ürünleri Lisanslı Depoculuk Yönetmeliğini, Hububat, Baklagiller ve Yağlı Tohumlar Lisanslı Depo Tebliğini ve 11 Mart 2026 tarihli kuruluş izni tebliğini listeler. Yalnız eski bir yönetmelik kopyasına dayanarak lisans şartı çıkarılmamalıdır. Proje kararı güncel konsolide metin ve yetkili kurumla doğrulanmalıdır. [17]',
 'Bakanlık ayrıca hububat, baklagiller ve yağlı tohumlar lisanslı depoları için inceleme rehberine yönlendirir. Uygulamanın sonraki sürümünde “lisanslı depo hedefleniyor mu?” ayrı bir müşteri girdisi olmalı; kalite sınıflandırma, kayıt ve denetim belgeleri ayrı iş paketi olarak izlenmelidir. Bu araştırmada işletmeye özel izin uygunluğu veya asgari lisans kapasitesi kararı verilmemiştir. [18]',
 'Silo projesinde yükler, çelik kabuk, temel ve deprem hesabı için uygulanacak standart seti proje mühendisi tarafından belirlenmelidir. JRC, Eurocode ailesinde ikinci nesle geçiş ve ülkeye özgü parametreleri ayrı ele alır. Bu nedenle standardın sadece adı değil; baskısı, ulusal eki, geçiş durumu ve proje kapsamında uygulanabilirliği kaydedilmelidir. Bu yazılım herhangi bir Eurocode hesap modülü uygulamamaktadır. [19]',
 'AFAD’ın broşürü Türkiye Bina Deprem Yönetmeliğinin 1 Ocak 2019’da yürürlüğe girdiğini bildirir. Bunun tek başına bütün silo yapılarının hesap yöntemini belirlediği varsayılmamalıdır; yapının kapsamı ve ilgili özel esaslar yetkin mühendis tarafından değerlendirilir. Arsa imarı, yapı ruhsatı, çevresel izinler, işyeri açılışı, yangın ve patlayıcı ortam yükümlülükleri de yer ve tesis niteliğine göre ayrıca incelenmelidir. [20]'
 ]},
 {id:'tedarik',title:'Üretici ve ekipman verisi stratejisi',paragraphs:[
 'İlk kaynak kümesi Türkiye’den Mysilo ve OBIAL; depolama ve bakım referansı olarak Brock; taşıma ekipmanları için Silos Córdoba; temizleme ve kurutma için Cimbria’dan oluşur. Bunlar doğrulanmış teknik kaynak örnekleridir, satın alma sıralaması veya fiyat karşılaştırması değildir. Marka logosu veya katalog görseli kullanma hakkı, teknik sayfaya erişimden otomatik doğmaz.',
 'Üretici kartı; firma, ürün ailesi, model kodu, tarih, kaynak URL, ölçü çizimi, hacim, yoğunluk esası, dolum/sıkışma katsayısı, yük sınırları ve model lisansını içermelidir. Kurutucu kartında kapasite ürün ve nem koşullarıyla; konveyörde yatay/eğimli debi, hız, motor ve mesafeyle; temizleyicide ürün, kirlilik ve temizlik seviyesiyle birlikte tutulmalıdır. Her güncellemede eski proje referansı korunmalıdır.',
 'Bütçe için çelik ve mekanik ekipman bedellerinden ayrı; temel ve altyapı, nakliye, gümrük, vinç, montaj, enerji bağlantısı, kontrol sistemi, test, eğitim, yedek parça ve proje hizmetleri gerekir. Sabit bir ton başı bedel saha koşullarını gizler. Güncel teklif alınmadığı için uygulamada parasal maliyet üretilmemiştir. Karşılaştırma ekranı ileride tarihli, kapsamı açık tekliflerden beslenmelidir.',
 'Üreticiden istenecek ilk paket: seçilen ailelerin güncel kapasite tablosu; ölçülü genel yerleşim çizimi; yük ve temel reaksiyonları; bağlantı noktaları; nominal ve ürün bazlı debi eğrileri; enerji bilgileri; bakım zarfları; kurulum kılavuzu; yeniden dağıtım izni olan STEP, IFC veya glTF modeller. Kamuya açık pazarlama modeli ile mühendislik onaylı ölçü modelinin veri düzeyi ayrı tutulmalıdır.'
 ]},
 {id:'assets',title:'3B varlıklar ve lisansları',paragraphs:[
 'İlk çalışan kütüphane sekiz özgün parametrik model içerir: düz tabanlı silo, konik silo, elevatör, kurutucu, temizleyici, alım çukuru, yaş ürün tamponu ve kontrol binası. Modeller bu proje için Three.js geometrisiyle oluşturulmuştur; üreticinin CAD dosyası değildir. Boyutları metre cinsindedir, düşey eksen Y’dir. GLB varlıkları yerel dosyalarda sunulur ve tesisin tamamı GLB olarak dışa aktarılabilir.',
 'Bulunan dış model: juninholiveira tarafından yayımlanan Grain Silo, Sketchfab sayfasında 10 Şubat 2016 tarihli ve Creative Commons Attribution-ShareAlike lisanslı görünmektedir. Kaynak kartına eklenmiştir; uygulamaya indirilmiş veya dahil edilmiş değildir. Bu modelin görsel referans niteliği, ölçü doğruluğunun veya mühendislik uygunluğunun doğrulandığı anlamına gelmez. [22]',
 'Sketchfab indirme API rehberi oturum açma gereksinimini ve modelle birlikte taşınması gereken atıf/lisans bilgisini açıklar. Sonraki entegrasyonda kullanıcı, kaynak, lisans sürümü, değişiklik kaydı ve dışa aktarılan türev dosyaların koşulları takip edilmelidir. Kamuya açık önizleme, sınırsız yeniden dağıtım izni olarak yorumlanmaz. [23]',
 'Three.js GLTFExporter, sahnenin glTF veya ikili GLB biçiminde verilmesini sağlar. Bu biçim görsel sahnenin taşınması için uygundur. BIM sınıfları, imalat toleransları veya onaylı mühendislik belgesi içerdiği varsayılmamalıdır. Yerel GLB manifestinde temsili geometri durumu ve kaynaklar bulunur. Tam proje JSON dosyası ise girdileri, sürümü, sonuçları ve uyarıları saklar. [24]'
 ]},
 {id:'yazilim',title:'Uygulama mimarisi ve geliştirme yolu',paragraphs:[
 'Silo Studio 0.1; React ve TypeScript arayüzü, Three.js sahnesi, tarayıcıda çalışan deterministik yerleşim motoru ve cihaz içi proje kaydı kullanır. Sunucu yalnızca yerel arayüzü sunar. Proje verileri harici hesaba gönderilmez; görsel model için uzak CDN veya harita servisi gerekmez. Kaynak bağlantıları isteğe bağlı olarak dış siteleri açar.',
 'Hesap motoru görselleştirmeden ayrıdır. Aynı girdiler aynı yerleşimi verir. JSON içe aktarımı doğrulanır ve sonuç dosyada yazılı olsa bile yeniden hesaplanır. Hatalı girdiler mevcut çalışan projenin üzerine sessizce uygulanmaz. Kapasite, sınır ve çakışma değişmezleri otomatik testlerle kontrol edilir. Kurutma kütle dengesi ayrıca sınanır.',
 'İlk sürümün kapsamı: tek ürün ve yoğunluk, dikdörtgen arsa, sabit sınır aralığı, çap/yükseklik aday araması, partiye göre asgari silo sayısı, isteğe bağlı kurutma/temizleme/havalandırma, 3B sahne, ölçülü 2B plan, ekipman listesi, uyarılar, proje JSON ve GLB çıktısı. Kurutucu veya elevatör gerçek SKU boyutlandırması, enerji ve maliyet tahmini, poligon arsa, arazi eğimi, otomatik ruhsat uygunluğu ve imalat projesi kapsam dışıdır.',
 'Önerilen bir sonraki geliştirme dilimi; müşteri kaydı ve birden fazla proje, çok ürün/parti dağılımı, poligon arsa ve engellerdir. Ardından üretici veri içe aktarma, bakım zarfları ve hat bağlantıları gelir. Son aşamada mühendis inceleme iş akışı, onay revizyonları ve teklif karşılaştırması eklenebilir. Her aşamanın tamamlanma ölçütü görünür bir ekran değil, doğru veriyle tekrar üretilebilir bir karar ve doğrulanmış çıktıdır.'
 ]},
 {id:'belirsizlik',title:'Doğrulanması gereken başlıklar',paragraphs:[
 'Kaynaklar 14 Eylül 2026 tarihinde incelendi. Web sayfalarının arama motorunda görünen güncellenme tarihleri, belgenin gerçek revizyon tarihi yerine kullanılmadı. Üretici PDF’lerinde açıkça okunamayan baskı tarihi “doğrulanamadı” olarak kaydedildi. Üretici verileri teknik aralık ve örnek performans için değerlendirildi; ticari performans iddiaları bağımsız olarak doğrulanmış sayılmadı.',
 'Kritik açık noktalar: müşteri ürünü ve depolama süresi, ölçülmüş yoğunluk, gerçek parsel ve kotlar, zemin, pik araç profili, saha iklimi, üretici boyut ve yük tabloları, elektrik/yakıt olanakları, kalite kriterleri, izin rejimi ve gerçek bütçe. Bunlar tamamlanmadan uygulamanın ürettiği yerleşim satın alma veya inşa onayı olarak kullanılmamalıdır.',
 'Katalog araması stokların hangi yıl ve kalite sınıfına ayrılacağını çözmez. Tek yoğunluk bütün ana silolara uygulanır. Silo kapasitesindeki pay ile kurutma sonrası kütle kaybı ayrı kavramlardır. Gösterilen taban kullanım oranı ekipmanların nominal tabanlarıyla hesaplanır; yolların, temellerin, servis zarflarının ve tüm mevzuat rezervlerinin toplam işgal oranı değildir.'
 ]},
];
