export type PortSettings={edge:'south'|'north'|'east'|'west';quayDepth:number;shipGap:number;shipBeam:number;shipLength:number;hatches:number};
export type DesignBasis={location:string;standard:string;snowLoad:number|null;windSpeed:number|null;seismicPga:number|null;soilBearing:number|null;corrosion:'unknown'|'C2'|'C3'|'C4'|'C5'|'CX';throughput:number|null};
export const DEFAULT_PORT:PortSettings={edge:'south',quayDepth:14,shipGap:3,shipBeam:20,shipLength:90,hatches:4};
export const DEFAULT_DESIGN:DesignBasis={location:'',standard:'',snowLoad:null,windSpeed:null,seismicPga:null,soilBearing:null,corrosion:'unknown',throughput:null};
export const portSettings=(p:{port?:PortSettings})=>p.port||DEFAULT_PORT;
export const designBasis=(p:{design?:DesignBasis})=>p.design||DEFAULT_DESIGN;
export function validPort(p:PortSettings){return p&&['south','north','east','west'].includes(p.edge)&&Number.isFinite(p.quayDepth)&&p.quayDepth>=8&&p.quayDepth<=60&&Number.isFinite(p.shipGap)&&p.shipGap>=1&&p.shipGap<=30&&Number.isFinite(p.shipBeam)&&p.shipBeam>=8&&p.shipBeam<=60&&Number.isFinite(p.shipLength)&&p.shipLength>=30&&p.shipLength<=350&&Number.isInteger(p.hatches)&&p.hatches>=1&&p.hatches<=10&&p.shipLength>=p.shipBeam*2.5&&p.shipLength-p.shipBeam*1.5>=p.hatches*4}
export function validDesign(d:DesignBasis){return d&&typeof d.location==='string'&&d.location.length<=160&&typeof d.standard==='string'&&d.standard.length<=160&&['unknown','C2','C3','C4','C5','CX'].includes(d.corrosion)&&Object.entries({snowLoad:30,windSpeed:150,seismicPga:3,soilBearing:10000,throughput:10000}).every(([k,max])=>{const v=d[k as keyof DesignBasis];return v===null||typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=max})}
export type CoastalSite={width:number;depth:number;facility?:string;port?:PortSettings};
export function portFrame(p:CoastalSite){const settings=portSettings(p),angle=({south:0,north:Math.PI,east:Math.PI/2,west:-Math.PI/2})[settings.edge],rotated=['east','west'].includes(settings.edge),width=rotated?p.depth:p.width,depth=rotated?p.width:p.depth,quayEnd=depth/2+settings.quayDepth;return{...settings,angle,width,depth,quayEnd,shipZ:quayEnd+settings.shipGap+settings.shipBeam/2}}
export function toCoast(p:CoastalSite,point:{x:number;z:number}){const {angle}=portFrame(p);return{x:point.x*Math.cos(angle)-point.z*Math.sin(angle),z:point.x*Math.sin(angle)+point.z*Math.cos(angle)}}
export function fromCoast(p:CoastalSite,point:{x:number;z:number}){const {angle}=portFrame(p);return{x:point.x*Math.cos(angle)+point.z*Math.sin(angle),z:-point.x*Math.sin(angle)+point.z*Math.cos(angle)}}
export function shoreBounds(p:CoastalSite){const f=portFrame(p),pts=[{x:-Math.max(f.width,f.shipLength)/2-10,z:-f.depth/2},{x:Math.max(f.width,f.shipLength)/2+10,z:f.shipZ+f.shipBeam/2+12}].flatMap(a=>[{x:a.x,z:-f.depth/2},{x:a.x,z:f.shipZ+f.shipBeam/2+12}]).map(a=>fromCoast(p,a));return{minX:Math.min(-p.width/2,...pts.map(a=>a.x)),maxX:Math.max(p.width/2,...pts.map(a=>a.x)),minZ:Math.min(-p.depth/2,...pts.map(a=>a.z)),maxZ:Math.max(p.depth/2,...pts.map(a=>a.z))}}
export function workingGround(p:CoastalSite){if(p.facility!=='port')return{width:p.width,depth:p.depth,x:0,z:0};const f=portFrame(p),offset=fromCoast(p,{x:0,z:f.quayDepth/2}),rotated=['east','west'].includes(f.edge);return{width:p.width+(rotated?f.quayDepth:0),depth:p.depth+(rotated?0:f.quayDepth),...offset}}
