'use client';
import {useState} from 'react';
import {ContactRound,Pencil} from 'lucide-react';
import type {User,ProjectRecord} from '@/lib/business';
import type {Customer} from '@/lib/editor';
import {api} from '@/lib/api-client';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {OfficeField,PanelTitle,Empty} from './fields';
export type CustomerRecord={id:string;ownerId:string;projectId:string;data:Customer;updatedAt:string};
const labels={firstName:'Ad',lastName:'Soyad',company:'Firma',email:'E-posta',phone:'Telefon',country:'Ülke',address:'Adres'};
export default function CustomersPanel({customers,users,projects,refresh}:{customers:CustomerRecord[];users:User[];projects:ProjectRecord[];refresh:()=>Promise<void>}){const [selected,setSelected]=useState<CustomerRecord|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');return <><PanelTitle eyebrow="MÜŞTERİ PORTFÖYÜ" title="Müşteriler"/>{customers.length?<div className="office-table-wrap"><table className="office-table"><thead><tr><th>Müşteri / firma</th><th>İletişim</th><th>Proje</th><th>Temsilci</th><th/></tr></thead><tbody>{customers.map(c=><tr key={c.id}><td><strong>{c.data.firstName} {c.data.lastName}</strong><small>{c.data.company||'Firma bilgisi bekleniyor'}</small></td><td>{c.data.email}<small>{c.data.phone}</small></td><td>{projects.find(p=>p.project.id===c.projectId)?.project.name}</td><td>{users.find(u=>u.id===c.ownerId)?.name}</td><td><button className="m-tool" aria-label="Müşteri bilgilerini düzenle" onClick={()=>{setSelected(c);setError('')}}><Pencil size={16}/></button></td></tr>)}</tbody></table></div>:<Empty><ContactRound size={32}/><h2>Henüz müşteri kaydı yok</h2><p>Proje sırasında girilen müşteri bilgileri burada toplanır.</p></Empty>}<Sheet open={!!selected} onOpenChange={v=>{if(!v)setSelected(null)}}><SheetContent className="mysilo-app office-sheet"><SheetHeader><SheetTitle>Müşteri bilgileri</SheetTitle><SheetDescription>Mevcut tekliflerin müşteri kayıtları korunur.</SheetDescription></SheetHeader>{selected&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('projects/'+selected.projectId+'/customer','PUT',selected.data);await refresh();setSelected(null)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{(Object.keys(labels) as (keyof Customer)[]).map(k=><OfficeField key={k} label={labels[k]}><input className="m-input" type={k==='email'?'email':'text'} maxLength={300} value={selected.data[k]} onChange={e=>setSelected({...selected,data:{...selected.data,[k]:e.target.value}})}/></OfficeField>)}{error&&<p className="form-error">{error}</p>}<button className="m-button primary full-width" disabled={busy}>Kaydet</button></form>}</SheetContent></Sheet></>}
