'use client';
import {useState} from 'react';
import {FileText,Download,ArrowUpRight} from 'lucide-react';
import type {Quote,User} from '@/lib/business';
import {downloadBlob} from '@/lib/project';
import {handlingName} from '@/lib/handling-catalog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {PanelTitle,Empty,dateLabel} from './fields';
export default function QuotesPanel({quotes,users}:{quotes:Quote[];users:User[]}){const [selected,setSelected]=useState<Quote|null>(null);return <><PanelTitle eyebrow="TEKLİF ARŞİVİ" title="Teklifler"/>{quotes.length?<div className="office-table-wrap"><table className="office-table"><thead><tr><th>Teklif / proje</th><th>Müşteri</th><th>Temsilci</th><th>Durum</th><th>Tarih</th><th/></tr></thead><tbody>{quotes.map(q=><tr key={q.id}><td><button className="table-link" onClick={()=>setSelected(q)}>{q.number}</button><small>{q.snapshot.project.name}</small></td><td>{q.snapshot.customer.company}<small>{q.snapshot.customer.firstName} {q.snapshot.customer.lastName}</small></td><td>{users.find(u=>u.id===q.ownerId)?.name}</td><td><span className="status-pill">Fiyat bekliyor · {q.currency}</span></td><td>{dateLabel(q.createdAt)}</td><td><button className="m-tool" aria-label={q.number+' detay'} onClick={()=>setSelected(q)}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div>:<Empty><FileText size={32}/><h2>Henüz teklif oluşturulmadı</h2><p>Proje indirildiğinde müşteri bilgileriyle teklif kaydı açılır.</p></Empty>}<Sheet open={!!selected} onOpenChange={v=>{if(!v)setSelected(null)}}><SheetContent className="mysilo-app office-sheet wide"><SheetHeader><SheetTitle>{selected?.number}</SheetTitle><SheetDescription>{selected?.snapshot.project.name} · Kaydedildiği andaki proje</SheetDescription></SheetHeader>{selected&&<><div className="office-card"><h2>{selected.snapshot.customer.company}</h2><p>{selected.snapshot.customer.firstName} {selected.snapshot.customer.lastName}</p><p>{selected.snapshot.customer.email}</p><p>{selected.snapshot.customer.phone}</p><small>{selected.snapshot.customer.address}</small></div><div className="office-info"><FileText size={18}/><p>Fiyatlandırma bekliyor · {selected.currency}. Tutar henüz hesaplanmadı.</p></div><div className="office-card"><h2>Teklif kapsamı</h2>{selected.snapshot.project.items.map((i,n)=><div className="detail-row" key={i.id}><span>{n+1}. {handlingName(i,'tr')}</span><small>{i.width} × {i.depth} × {i.height} m</small></div>)}</div><div className="office-card"><h2>Yük profili</h2><p>{selected.snapshot.project.loadProfile?.name||'Onaylı profil bekleniyor'}</p><small>{selected.snapshot.project.loadProfile?.source}</small><p>Proje sürümü: {selected.snapshot.projectRevision}</p></div><button className="m-button primary full-width" onClick={()=>downloadBlob(new Blob([JSON.stringify(selected,null,2)],{type:'application/json'}),selected.number+'.json')}><Download size={17}/>Teklif kaydını indir</button></>}</SheetContent></Sheet></>}
