'use client';
import {useState} from 'react';
import {Plus,Pencil,UsersRound,ShieldCheck} from 'lucide-react';
import type {User} from '@/lib/business';
import {api} from '@/lib/api-client';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {OfficeField,PanelTitle} from './fields';
const blank={id:'',name:'',email:'',role:'sales',active:true,password:''};
export default function UsersPanel({users,refresh}:{users:User[];refresh:()=>Promise<void>}){const [form,setForm]=useState(blank),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');return <><PanelTitle eyebrow="EKİP" title="Kullanıcılar"><button className="m-button primary" onClick={()=>{setForm(blank);setError('');setOpen(true)}}><Plus size={17}/>Kullanıcı ekle</button></PanelTitle><div className="office-table-wrap"><table className="office-table"><thead><tr><th>Kullanıcı</th><th>Yetki</th><th>Durum</th><th/></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><div className="person-cell"><span>{u.name.split(' ').map(s=>s[0]).slice(0,2).join('')}</span><div><strong>{u.name}</strong><small>{u.email}</small></div></div></td><td><span className="role-badge">{u.role==='admin'?<ShieldCheck size={14}/>:<UsersRound size={14}/>} {u.role==='admin'?'Yönetici':'Satış temsilcisi'}</span></td><td><span className={`status-pill ${u.active?'approved':''}`}>{u.active?'Aktif':'Pasif'}</span></td><td><button className="m-tool" aria-label={u.name+' düzenle'} onClick={()=>{setForm({...u,active:!!u.active,password:''});setError('');setOpen(true)}}><Pencil size={16}/></button></td></tr>)}</tbody></table></div><Sheet open={open} onOpenChange={setOpen}><SheetContent className="mysilo-app office-sheet"><SheetHeader><SheetTitle>{form.id?'Kullanıcıyı düzenle':'Yeni kullanıcı'}</SheetTitle><SheetDescription>Giriş ve erişim bilgileri</SheetDescription></SheetHeader><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('admin/users','POST',form);await refresh();setOpen(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><OfficeField label="Ad soyad"><input className="m-input" required maxLength={200} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></OfficeField><OfficeField label="E-posta"><input className="m-input" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></OfficeField><OfficeField label="Yetki"><select className="m-input" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="sales">Satış temsilcisi</option><option value="admin">Yönetici</option></select></OfficeField><OfficeField label={form.id?'Yeni şifre · boş bırakırsanız korunur':'Şifre · en az 12 karakter'}><input className="m-input" autoComplete="new-password" type="password" minLength={12} maxLength={128} required={!form.id} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></OfficeField><label className="office-check"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Aktif kullanıcı</label>{error&&<p role="alert" className="form-error">{error}</p>}<button disabled={busy} className="m-button primary full-width">Kaydet</button></form></SheetContent></Sheet></>}
