'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {ArrowRight,LockKeyhole,Mail,Eye,EyeOff,LoaderCircle,ShieldCheck} from 'lucide-react';
import {api} from '@/lib/api-client';
import {LANGUAGES,t,type Lang} from '@/lib/i18n';
import {PREFS_KEY} from '@/lib/editor';
import type {User} from '@/lib/business';
export default function LoginForm({backoffice=false}:{backoffice?:boolean}){
 const [lang,setLang]=useState<Lang>('tr');
 useEffect(()=>{try{const prefs=JSON.parse(localStorage.getItem(PREFS_KEY)||'{}');if(LANGUAGES.some(l=>l.id===prefs.language))setLang(prefs.language)}catch{}},[]);
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{api<{user:User}>('auth/me').then(({user})=>{if(!backoffice||user.role==='admin')window.location.replace(backoffice?'/backoffice':'/')}).catch(()=>{})},[backoffice]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const {user}=await api<{user:User}>('auth/login','POST',{email,password});if(backoffice&&user.role!=='admin'){setError('Bu hesabın yönetim paneli yetkisi yok.');return}window.location.assign(backoffice?'/backoffice':'/')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="mysilo-app auth-page"><section className="auth-visual"><img className="auth-brand" src="/brand/logo.png" alt="Mysilo"/><div className="auth-scene"><img src="/mysilo/flat.png" alt=""/><img src="/mysilo/flat.png" alt=""/><img src="/mysilo/flat.png" alt=""/></div><div className="auth-caption"><span>MYSiLO · STUDIO</span><h1>Bir fikirden<br/>bir tesise.</h1><p>Projelendirme. Yerleşim. Teklif.</p></div><span className="auth-edition">Tesis tasarım platformu</span></section><section className="auth-entry"><form onSubmit={submit} dir={lang==='ar'?'rtl':'ltr'}><select className="login-language" aria-label={t(lang,'language')} value={lang} onChange={e=>{const language=e.target.value as Lang;setLang(language);try{localStorage.setItem(PREFS_KEY,JSON.stringify({language,currency:'TRY'}))}catch{}}}>{LANGUAGES.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><span className="auth-symbol">{backoffice?<ShieldCheck size={25}/>:<LockKeyhole size={25}/>}</span><p className="eyebrow">{backoffice?'BACKOFFICE':t(lang,'loginWelcome')}</p><h2>{backoffice?'Yönetici girişi':t(lang,'loginTitle')}</h2><p className="muted">{backoffice?'Kullanıcılar, bölgeler ve teklifler.':t(lang,'loginHint')}</p><label className="m-field"><span>{t(lang,'email')}</span><div className="auth-input"><Mail size={18}/><input autoComplete="username" type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="ad@firma.com"/></div></label><label className="m-field"><span>{t(lang,'password')}</span><div className="auth-input"><LockKeyhole size={18}/><input autoComplete="current-password" type={visible?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} required maxLength={128}/><button type="button" aria-label={t(lang,visible?'hidePassword':'showPassword')} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{error&&<p role="alert" className="form-error">{error}</p>}<button disabled={busy} className="m-button primary full-width">{busy?<LoaderCircle className="spin" size={18}/>:<>{t(lang,'signIn')}<ArrowRight size={18}/></>}</button><p className="auth-footnote">{t(lang,'accountHelp')}</p></form></section></main>
}
